//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Search
{
    public partial class SummaryReport
    {
    }
}
