(function ($) {
    "use strict";
    var pageUrl = "ImportBilling.aspx", previewTable = null, historyTable = null, importToken = "";
    function popup(icon, title, text) { return Swal.fire({ icon: icon, title: title, text: text, confirmButtonText: "OK" }); }
    function call(name, data) { return $.ajax({ url: pageUrl + "/" + name, type: "POST", contentType: "application/json; charset=utf-8", dataType: "json", data: JSON.stringify(data || {}) }).then(function (response) { if (response && response.d && response.d.Success === false) return $.Deferred().reject({ userMessage: response.d.Message }).promise(); return response; }); }
    function error(xhr) { if (xhr && xhr.userMessage) return xhr.userMessage; try { return JSON.parse(xhr.responseText).Message || "A system error occurred."; } catch (e) { return "A system error occurred."; } }
    function populatePeriods() { var names = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], now = new Date(), months = "", years = ""; $.each(names, function (i, name) { months += '<option value="' + (i + 1) + '"' + (i === now.getMonth() ? " selected" : "") + '>' + name + "</option>"; }); for (var y = now.getFullYear() + 1; y >= 2015; y--) years += '<option value="' + y + '"' + (y === now.getFullYear() ? " selected" : "") + '>' + y + "</option>"; $("#ibMonth,#ibHistoryMonth").html(months); $("#ibYear,#ibHistoryYear").html(years); }
    function loadProjects() { call("GetProjects").done(function (r) { var html = '<option value="">Select Project</option>'; $.each(r.d || [], function (_, p) { html += '<option value="' + p.ID + '">' + $("<div>").text(p.Name).html() + "</option>"; }); $("#ibProject,#ibHistoryProject").html(html); }).fail(function (x) { popup("error", "Project Load Failed", error(x)); }); }
    function period(prefix) { return { projectId: parseInt($("#" + prefix + "Project").val(), 10) || 0, billingMonth: parseInt($("#" + prefix + "Month").val(), 10) || 0, billingYear: parseInt($("#" + prefix + "Year").val(), 10) || 0 }; }
    function valid(p) { if (!p.projectId) { popup("warning", "Validation", "Please select a project."); return false; } if (!p.billingMonth || !p.billingYear) { popup("warning", "Validation", "Please select a billing month and year."); return false; } return true; }
    function columns(result) { return $.map(result.Columns || [], function (name) { return { data: name, title: name, defaultContent: "", className: "text-nowrap", render: $.fn.dataTable.render.text() }; }); }
    function table(selector, current, result, fileName, title) { if (current) current.destroy(); $(selector).empty(); return $(selector).DataTable({ data: result.Rows || [], columns: columns(result), scrollX: true, scrollY: "55vh", scrollCollapse: true, autoWidth: false, pageLength: 25, lengthMenu: [[25, 50, 100, -1], [25, 50, 100, "All"]], dom: "<'row mb-2'<'col-sm-12 col-md-6'B><'col-sm-12 col-md-6'f>><'row'<'col-sm-12'tr>><'row mt-2'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>", buttons: [{ extend: "excelHtml5", text: '<i class="fas fa-file-excel"></i> Export Excel', className: "btn btn-success", filename: fileName, title: title, exportOptions: { modifier: { search: "applied", order: "applied", page: "all" } } }] }); }
    function downloadTemplate() {
        var projectId = parseInt($("#ibProject").val(), 10) || 0;
        if (!projectId) { popup("warning", "Validation", "Please select a project before downloading its billing template."); return; }
        $("#ibDownloadTemplate").prop("disabled", true);
        call("DownloadTemplate", { projectId: projectId }).done(function (r) {
            var result = r.d, binary = atob(result.FileBase64), bytes = new Uint8Array(binary.length);
            for (var i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
            var url = URL.createObjectURL(new Blob([bytes], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })), link = document.createElement("a");
            link.href = url; link.download = result.FileName; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url);
            popup("success", "Template Downloaded", result.Message);
        }).fail(function (x) { popup("error", "Template Download Failed", error(x)); }).always(function () { $("#ibDownloadTemplate").prop("disabled", false); });
    }
    function resetPreview() { importToken = ""; $("#ibPreviewCard").hide(); $("#ibVerify,#ibSend").prop("disabled", true); if (previewTable) { previewTable.destroy(); previewTable = null; } $("#ibTable").empty(); }
    function importExcel() { var p = period("ib"), file = $("#ibFile")[0].files[0]; if (!valid(p)) return; if (!file) { popup("warning", "Validation", "Please select a billing Excel file."); return; } if (!/\.xlsx?$/i.test(file.name)) { popup("warning", "Invalid File", "Only .xls and .xlsx billing files are accepted."); return; } if (file.size > 10 * 1024 * 1024) { popup("warning", "Invalid File", "The selected file exceeds the 10 MB limit."); return; } resetPreview(); $("#ibImport").prop("disabled", true); $("#ibLoading").show(); var reader = new FileReader(); reader.onerror = function () { $("#ibImport").prop("disabled", false); $("#ibLoading").hide(); popup("error", "Import Failed", "The selected file could not be read."); }; reader.onload = function (e) { var base64 = String(e.target.result).split(",")[1] || ""; call("ImportExcel", $.extend({}, p, { fileName: file.name, fileBase64: base64 })).done(function (r) { var result = r.d, project = $("#ibProject option:selected").text().replace(/[^a-z0-9_-]+/gi, "_"); importToken = result.Token; previewTable = table("#ibTable", previewTable, result, "Imported_Billing_" + project + "_" + p.billingYear + "_" + p.billingMonth, "Imported Billing"); $("#ibSummary").text(result.RowCount + " imported record(s) - Pending verification"); $("#ibPreviewCard").show(); $("#ibVerify").prop("disabled", false); previewTable.columns.adjust(); popup("success", "Import Successful", result.Message); }).fail(function (x) { popup("error", "Import Failed", error(x)); }).always(function () { $("#ibImport").prop("disabled", false); $("#ibLoading").hide(); }); }; reader.readAsDataURL(file); }
    function verify() { if (!importToken) { popup("warning", "Validation", "Import a billing Excel file first."); return; } Swal.fire({ icon: "question", title: "Verify imported billing?", text: "Please confirm that the imported preview is correct.", showCancelButton: true, confirmButtonText: "Verify", confirmButtonColor: "#28a745" }).then(function (a) { if (!a.isConfirmed) return; $("#ibVerify,#ibSend").prop("disabled", true); call("VerifyImport", { token: importToken }).done(function (r) { $("#ibSummary").html('<span class="ib-status ib-verified">Verified</span> ' + r.d.Count + " billing record(s)"); $("#ibSend").prop("disabled", false); popup("success", "Verification Successful", r.d.Message); }).fail(function (x) { $("#ibVerify").prop("disabled", false); popup("error", "Verification Failed", error(x)); }); }); }
    function send() { if (!importToken) return; Swal.fire({ icon: "warning", title: "Send billing to Accounts?", text: "Verified billing records will be inserted using the existing billing process.", showCancelButton: true, confirmButtonText: "Send to Accounts", confirmButtonColor: "#17a2b8" }).then(function (a) { if (!a.isConfirmed) return; $("#ibVerify,#ibSend").prop("disabled", true); call("SendToAccounts", { token: importToken }).done(function (r) { popup("success", "Sent to Accounts", r.d.Message).then(function () { $("#ibFile").val(""); resetPreview(); }); }).fail(function (x) { $("#ibSend").prop("disabled", false); popup("error", "Send Failed", error(x)); }); }); }
    function history() { var p = period("ibHistory"); if (!valid(p)) return; $("#ibHistoryShow").prop("disabled", true); $("#ibHistoryLoading").show(); call("GetBillingHistory", p).done(function (r) { var result = r.d, project = $("#ibHistoryProject option:selected").text().replace(/[^a-z0-9_-]+/gi, "_"); historyTable = table("#ibHistoryTable", historyTable, result, "Billing_History_" + project + "_" + p.billingYear + "_" + p.billingMonth, "Billing History"); $("#ibHistorySummary").text(result.RowCount + " record(s) sent to Accounts"); $("#ibHistoryCard").show(); historyTable.columns.adjust(); if (!result.RowCount) popup("info", "No History", "No billing records were found for the selected period."); }).fail(function (x) { popup("error", "History Load Failed", error(x)); }).always(function () { $("#ibHistoryShow").prop("disabled", false); $("#ibHistoryLoading").hide(); }); }
    $(function () { populatePeriods(); loadProjects(); $("#ibImport").on("click", importExcel); $("#ibDownloadTemplate").on("click", downloadTemplate); $("#ibVerify").on("click", verify); $("#ibSend").on("click", send); $("#ibHistoryShow").on("click", history); $("#ibProject").on("change", function () { resetPreview(); $("#ibDownloadTemplate").prop("disabled", !this.value); }); $("#ibMonth,#ibYear").on("change", resetPreview); });
})(jQuery);
