var page = 'ManagerDashboard.aspx', reAllUsers = []; document.addEventListener('DOMContentLoaded', function () { bindManagerTabs(); setDates(); OLT.call(page, 'GetProjects').then(function (r) { [mgrProject, dealProject, hourlyProject, reProject].forEach(function (s) { OLT.options(s, r, ['ProjectID'], ['ProjectName'], 'Select project'); }); }); mgrProject.onchange = function () { clearReport(); if (mgrProject.value) loadFilters(); else clearFilters(); }; dealProject.onchange = function () { loadDeals(dealProject, dealNumber, 'All deals'); }; hourlyProject.onchange = function () { loadDeals(hourlyProject, hourlyDeal, 'All deals'); }; reProject.onchange = loadReProject; reDeal.onchange = enableReProcess; reProcess.onchange = loadReUsers; reFromUser.onchange = function () { renderReTargets(); loadReOrders(); }; });
var pmaUsers = []; document.addEventListener('DOMContentLoaded', function () { OLT.call(page, 'GetProjects').then(function (r) { OLT.options(pmaProject, r, ['ProjectID'], ['ProjectName'], 'Select project'); }); pmaProject.onchange = loadProjectData; pmaDeal.onchange = enableProcess; pmaProcess.onchange = loadLoans; pmaUser.onchange = showUserCount; });
function loadProjectData() { pmaDeal.disabled = true; pmaProcess.disabled = true; pmaUser.disabled = true; pmaRows.innerHTML = '<tr><td colspan="9" class="olt-empty">Loading...</td></tr>'; if (!pmaProject.value) return; Promise.all([OLT.call(page, 'GetDeals', { projectId: +pmaProject.value }), OLT.call(page, 'GetUsers', { projectId: +pmaProject.value })]).then(function (r) { OLT.options(pmaDeal, r[0], ['DealNo', 'DealNumber', 'Deal'], ['DealNo', 'DealNumber', 'Deal'], 'Select deal'); pmaDeal.disabled = false; pmaUsers = r[1]; pmaUser.innerHTML = '<option value="">Select user</option>'; pmaUsers.forEach(function (x) { var o = document.createElement('option'); o.value = x.UserID; o.textContent = x.UserName + ' (' + x.ActiveCount + ' active)'; pmaUser.appendChild(o); }); pmaUser.disabled = false; pmaRows.innerHTML = '<tr><td colspan="9" class="olt-empty">Select deal and process.</td></tr>'; }).catch(showAllocationError); }
function enableProcess() { pmaProcess.disabled = true; pmaProcess.innerHTML = '<option value="">Loading process flow...</option>'; pmaRows.innerHTML = '<tr><td colspan="9" class="olt-empty">Select process.</td></tr>'; if (!pmaDeal.value) return; OLT.call(page, 'GetFlow', { projectId: +pmaProject.value, dealNumber: pmaDeal.value }).then(function (r) { OLT.options(pmaProcess, r, ['ProcessID'], ['ProcessName'], 'Select process'); pmaProcess.disabled = false; }).catch(showAllocationError); }
function loadLoans() { if (!pmaProject.value || !pmaDeal.value || !pmaProcess.value) return; pmaRows.innerHTML = '<tr><td colspan="9" class="olt-empty">Loading eligible orders...</td></tr>'; OLT.call(page, 'GetEligibleLoans', { projectId: +pmaProject.value, dealNumber: pmaDeal.value, processId: +pmaProcess.value }).then(function (r) { var projectName = pmaProject.options[pmaProject.selectedIndex].text, processName = pmaProcess.options[pmaProcess.selectedIndex].text; pmaRows.innerHTML = r.length ? r.map(function (x) { return '<tr><td><input type="checkbox" class="mgr-select pma-check" value="' + OLT.esc(x.LoanNumber) + '" onchange="limitSelection(this)"/></td><td>' + esc(projectName) + '</td><td>' + esc(pmaDeal.value) + '</td><td>' + esc(processName) + '</td><td>' + esc(x.LoanNumber) + '</td><td>—</td><td>Eligible</td><td>—</td><td>—</td></tr>'; }).join('') : '<tr><td colspan="9" class="olt-empty">No eligible orders found.</td></tr>'; }).catch(showAllocationError); }
function limitSelection(changed) { var selected = document.querySelectorAll('.pma-check:checked'); if (selected.length > 2) { changed.checked = false; OLT.alert('Select a maximum of two orders.', true); } }
function showUserCount() { var u = pmaUsers.filter(function (x) { return String(x.UserID) === String(pmaUser.value); })[0]; pmaUserNote.textContent = u ? u.ActiveCount + ' active Pending/In Process order(s).' : ''; }

var managerDetailRows = [], managerCharts = {};
document.addEventListener('DOMContentLoaded', function () { mgrProject.addEventListener('change', function () { loadDeals(mgrProject, mgrDeal, 'All deals'); }); mgrDeal.addEventListener('change', loadManagerDealProcesses); });
var reCurrentOrders = [];

function allocateSelected() {
    var loans = [].slice.call(document.querySelectorAll('.pma-check:checked')).map(function (x) { return x.value; });

    if (!pmaUser.value) {
        OLT.alert('Please select a user.', true);
        return;
    }

    if (!loans.length || loans.length > 2) {
        OLT.alert('Select one or two orders.', true);
        return;
    }

    OLT.call(page, 'AllocateOrders', { projectId: +pmaProject.value, dealNumber: pmaDeal.value, processId: +pmaProcess.value, targetUserId: +pmaUser.value, loanNumbers: loans }).then(function (r) {

        if (!r || r.Success !== true) {
            OLT.alert(r && r.Message ? r.Message : 'Allocation failed.', true);
            return;
        }

        OLT.alert(r.Message); loadProjectData();

    }).catch(showAllocationError);
}
function showAllocationError() { OLT.alert('The requested action could not be completed. Please try again.', true); }
function bindManagerTabs() { function activate(b) { document.querySelector('.mgr-tab.active').classList.remove('active'); document.querySelector('.mgr-panel.active').classList.remove('active'); b.classList.add('active'); document.getElementById(b.dataset.panel).classList.add('active'); mgrActivePanel.value = b.dataset.panel; } [].slice.call(document.querySelectorAll('.mgr-tab')).forEach(function (b) { b.onclick = function () { activate(b); }; }); var saved = document.querySelector('.mgr-tab[data-panel="' + mgrActivePanel.value + '"]'); if (saved && !saved.classList.contains('active')) activate(saved); }
function setDates() { var e = new Date(), s = new Date(); s.setDate(e.getDate() - 30); mgrFrom.value = iso(s); mgrTo.value = iso(e); hourlyDate.value = iso(e); } function iso(d) { return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0'); }
function clearFilters() { mgrProcess.innerHTML = '<option value="0">All processes</option>'; mgrUser.innerHTML = '<option value="0">All users</option>'; }
function clearReport() { managerDetailRows = []; renderSummary([]); renderDetails([]); }
function loadFilters() { var id = +mgrProject.value; if (!id) { clearFilters(); return; } Promise.all([OLT.call(page, 'GetProcesses', { projectId: id }), OLT.call(page, 'GetUsers', { projectId: id })]).then(function (r) { OLT.options(mgrProcess, r[0], ['ProcessID'], ['ProcessName'], 'All processes'); mgrProcess.options[0].value = '0'; OLT.options(mgrUser, r[1], ['UserID'], ['UserName'], 'All users'); mgrUser.options[0].value = '0'; }).catch(showError); }
function resetManagerFilters() { mgrProject.value = ''; mgrDeal.innerHTML = '<option value="">All deals</option>'; mgrDeal.disabled = true; mgrStatus.value = ''; mgrProductivityType.value = ''; setDates(); clearFilters(); clearReport(); }
function loadManagerDealProcesses() { if (!mgrProject.value || !mgrDeal.value) { loadFilters(); return; } OLT.call(page, 'GetFlow', { projectId: +mgrProject.value, dealNumber: mgrDeal.value }).then(function (rows) { OLT.options(mgrProcess, rows || [], ['ProcessID'], ['ProcessName'], 'All processes'); mgrProcess.options[0].value = '0'; }).catch(showError); }
function loadManagerReport() { var projectId = +mgrProject.value; if (!projectId) { OLT.alert('Please select Project #.', true); return; } if (!mgrFrom.value || !mgrTo.value || mgrFrom.value > mgrTo.value) { OLT.alert('Please enter a valid date range.', true); return; } OLT.call(page, 'GetReport', { projectId: projectId, dealNumber: mgrDeal.value, processId: +mgrProcess.value || 0, userId: +mgrUser.value || 0, status: mgrStatus.value, productivityType: mgrProductivityType.value, fromDate: mgrFrom.value, toDate: mgrTo.value }).then(function (r) { if (typeof r === 'string') r = JSON.parse(r); renderSummary(r.table0 || []); managerDetailRows = r.table1 || []; renderDetails(managerDetailRows); }).catch(showError); }
function renderSummary(rows) { summaryRows.innerHTML = rows.length ? rows.map(function (x) { return '<tr><td>' + esc(x.ProjectName) + '</td><td>' + esc(x.ProcessName) + '</td><td>' + esc(x.UserName) + '</td><td>' + x.TotalOrders + '</td><td>' + x.PendingOrders + '</td><td>' + x.InProcessOrders + '</td><td>' + x.HoldOrders + '</td><td>' + x.CompletedOrders + '</td><td class="mgr-duration">' + duration(x.AverageTATSeconds) + '</td><td class="mgr-duration">' + duration(x.TotalHoldTATSeconds) + '</td></tr>'; }).join('') : '<tr><td colspan="10" class="olt-empty">No summary records found.</td></tr>'; }
function renderDetails(rows) { var c = { total: rows.length, pending: 0, process: 0, hold: 0, completed: 0 }, users = {}, processes = {}, configured = false, totalSeconds = 0, today = iso(new Date()), completedToday = 0, pendingToday = 0; rows.forEach(function (x) { users[x.UserID || x.UserName] = true; processes[x.ProcessID || x.ProcessName] = true; configured = configured || !!x.ProductivityType; totalSeconds += +x.TotalTATSeconds || 0; if (x.AssignmentStatus === 'Pending') c.pending++; else if (x.AssignmentStatus === 'In Process') c.process++; else if (x.AssignmentStatus === 'Hold') c.hold++; else if (x.AssignmentStatus === 'Completed') c.completed++; if (dateKey(x.CompletedDate) === today) completedToday++; if (dateKey(x.AssignedDate) === today && x.AssignmentStatus !== 'Completed') pendingToday++; }); var actual = groupProductivity(rows); kTotal.textContent = c.total; kPending.textContent = c.pending; kProcess.textContent = c.process; kHold.textContent = c.hold; kCompleted.textContent = c.completed; kUsers.textContent = Object.keys(users).length; kProcesses.textContent = Object.keys(processes).length; kCompletedToday.textContent = completedToday; kPendingToday.textContent = pendingToday; kAverageTime.textContent = duration(rows.length ? totalSeconds / rows.length : 0); kProductivity.textContent = configured ? actual.toFixed(1) + '%' : '—'; kTargetProductivity.textContent = configured ? '100%' : '—'; kActualProductivity.textContent = configured ? actual.toFixed(1) + '%' : '—'; kProductivityVariance.textContent = configured ? (actual - 100).toFixed(1) + '%' : '—'; renderDetailTable(rows); renderManagerCharts(rows); }
function renderDetailTable(rows) { detailRows.innerHTML = rows.length ? rows.map(function (x) { var worked = x.ManualDurationMinutes == null ? '—' : workedDuration(x.ManualDurationMinutes); return '<tr><td>' + esc(x.ProjectName) + '</td><td>' + esc(x.DealNumber) + '</td><td>' + esc(x.LoanNumber) + '</td><td>' + esc(x.ProcessName) + '</td><td>' + esc(x.UserName) + '</td><td>' + esc(x.AssignmentStatus) + '</td><td>' + fmtDate(x.AssignedDate) + '</td><td>' + fmtDate(x.StartedDate) + '</td><td>' + fmtTime(x.StartedDate) + '</td><td>' + fmtDate(x.CompletedDate) + '</td><td>' + fmtTime(x.CompletedDate) + '</td><td>' + esc(x.ProductivityType) + '</td><td>' + esc(x.TargetDisplay) + '</td><td>' + ((+x.ProductivityPercent || 0) ? (+x.ProductivityPercent).toFixed(1) + '%' : '—') + '</td><td>' + duration(x.HoldTATSeconds) + '</td><td>' + duration(x.TotalTATSeconds) + '</td><td>' + worked + '</td><td>' + esc(x.FeedbackStatus) + '</td><td>' + esc(x.LastRemark) + '</td></tr>'; }).join('') : '<tr><td colspan="19" class="olt-empty">No detail records found.</td></tr>'; }
function dateKey(value) { var n = parseInt(String(value || '').replace(/\D/g, ''), 10), d = n ? new Date(n) : new Date(value); return isNaN(d.getTime()) ? '' : iso(d); }
function grouped(rows, key) { var map = {}; rows.forEach(function (x) { var name = x[key] || 'Unspecified'; if (!map[name]) map[name] = []; map[name].push(x); }); return map; }
function createManagerChart(id, type, labels, datasets, click, stacked) { if (managerCharts[id]) managerCharts[id].destroy(); managerCharts[id] = new Chart(document.getElementById(id).getContext('2d'), { type: type, data: { labels: labels, datasets: datasets }, options: { responsive: true, maintainAspectRatio: false, onClick: click || null, scales: type === 'doughnut' ? {} : { xAxes: [{ stacked: !!stacked }], yAxes: [{ stacked: !!stacked, ticks: { beginAtZero: true } }] } } }); }
function statusDatasets(groups, labels) { var colors = ['#f59e0b', '#0ea5e9', '#22c55e']; return ['Pending', 'In Process', 'Completed'].map(function (status, i) { return { label: status, backgroundColor: colors[i], data: labels.map(function (name) { return groups[name].filter(function (x) { return x.AssignmentStatus === status; }).length; }) }; }); }
function average(rows, field) { var values = rows.map(function (x) { return +x[field] || 0; }).filter(function (x) { return x > 0; }); return values.length ? values.reduce(function (a, b) { return a + b; }, 0) / values.length : 0; }
function groupProductivity(rows) { var hourly = rows.filter(function (x) { return x.ProductivityType === 'Hourly Productivity' && +x.ProductivityPercent > 0; }); return hourly.length ? average(hourly, 'ProductivityPercent') : (rows.length ? rows.filter(function (x) { return x.AssignmentStatus === 'Completed'; }).length / rows.length * 100 : 0); }
function drillHandler(labels, field, withStatus) { return function (_, elements) { if (!elements.length) return; var label = labels[elements[0]._index], status = withStatus ? ['Pending', 'In Process', 'Completed'][elements[0]._datasetIndex] : ''; renderDetailTable(managerDetailRows.filter(function (x) { return x[field] === label && (!status || x.AssignmentStatus === status); })); }; }
function renderManagerCharts(rows) { if (typeof Chart === 'undefined') return; var projects = grouped(rows, 'ProjectName'), deals = grouped(rows, 'DealNumber'), processes = grouped(rows, 'ProcessName'), users = grouped(rows, 'UserName'), projectNames = Object.keys(projects), dealNames = Object.keys(deals), processNames = Object.keys(processes), userNames = Object.keys(users); createManagerChart('chartProjectStatus', 'bar', projectNames, statusDatasets(projects, projectNames), drillHandler(projectNames, 'ProjectName', true), true); createManagerChart('chartDealStatus', 'bar', dealNames, statusDatasets(deals, dealNames), drillHandler(dealNames, 'DealNumber', true), true); createManagerChart('chartProcessProductivity', 'bar', processNames, [{ label: 'Target %', backgroundColor: '#94a3b8', data: processNames.map(function () { return 100; }) }, { label: 'Actual %', backgroundColor: '#8b5cf6', data: processNames.map(function (n) { return groupProductivity(processes[n]); }) }], drillHandler(processNames, 'ProcessName', false), false); createManagerChart('chartUserProductivity', 'bar', userNames, [{ label: 'Assigned', backgroundColor: '#64748b', data: userNames.map(function (n) { return users[n].length; }) }, { label: 'Completed', backgroundColor: '#22c55e', data: userNames.map(function (n) { return users[n].filter(function (x) { return x.AssignmentStatus === 'Completed'; }).length; }) }, { label: 'Pending', backgroundColor: '#f59e0b', data: userNames.map(function (n) { return users[n].filter(function (x) { return x.AssignmentStatus !== 'Completed'; }).length; }) }, { label: 'Productivity %', backgroundColor: '#8b5cf6', data: userNames.map(function (n) { return groupProductivity(users[n]); }) }], drillHandler(userNames, 'UserName', false), false); var days = {}; rows.forEach(function (x) { var day = dateKey(x.CompletedDate); if (day) (days[day] = days[day] || []).push(x); }); var dayNames = Object.keys(days).sort(); createManagerChart('chartDailyTrend', 'line', dayNames, [{ label: 'Completed Loans', borderColor: '#0f7899', backgroundColor: 'rgba(15,120,153,.15)', fill: true, data: dayNames.map(function (d) { return days[d].length; }) }]); var statuses = ['Pending', 'In Process', 'Completed']; createManagerChart('chartStatusDistribution', 'doughnut', statuses, [{ backgroundColor: ['#f59e0b', '#0ea5e9', '#22c55e'], data: statuses.map(function (s) { return rows.filter(function (x) { return x.AssignmentStatus === s; }).length; }) }], function (_, elements) { if (elements.length) renderDetailTable(managerDetailRows.filter(function (x) { return x.AssignmentStatus === statuses[elements[0]._index]; })); }); }
function loadDeals(projectSelect, dealSelect, placeholder) { dealSelect.disabled = true; dealSelect.innerHTML = '<option value="">' + placeholder + '</option>'; if (!projectSelect.value) return; OLT.call(page, 'GetDeals', { projectId: +projectSelect.value }).then(function (r) { OLT.options(dealSelect, r, ['DealNo', 'DealNumber', 'Deal'], ['DealNo', 'DealNumber', 'Deal'], placeholder); dealSelect.disabled = false; }).catch(showError); }
function loadDealDashboard() { if (!dealProject.value) { OLT.alert('Please select Project #.', true); return; } OLT.call(page, 'GetDealDashboard', { projectId: +dealProject.value, dealNumber: dealNumber.value }).then(function (r) { dealRows.innerHTML = r.length ? r.map(function (x) { return '<tr><td>' + esc(x.DealNumber) + '</td><td>' + x.DealCount + '</td><td>' + fmtDate(x.ReceivedDate) + '</td><td>' + fmtDate(x.DueDate) + '</td><td>' + esc(x.ProcessName) + '</td><td>' + x.PendingOrders + '</td><td>' + x.CompletedOrders + '</td><td>' + x.HoldOrders + '</td><td>' + x.SkippedOrders + '</td><td>' + x.TodayInProcess + '</td><td>' + x.TodayCompleted + '</td><td>' + x.TodayHold + '</td></tr>'; }).join('') : '<tr><td colspan="12" class="olt-empty">No deal records found.</td></tr>'; }).catch(showError); }
function loadHourly() { if (!hourlyProject.value) { OLT.alert('Please select Project #.', true); return; } OLT.call(page, 'GetHourlyProduction', { projectId: +hourlyProject.value, reportDate: hourlyDate.value, dealNumber: hourlyDeal.value }).then(function (r) { hourlyRows.innerHTML = r.length ? r.map(function (x) { return '<tr><td>' + esc(x.DealNumber) + '</td><td>' + esc(x.ProcessName) + '</td><td>' + x.H10AM + '</td><td>' + x.H12PM + '</td><td>' + x.H02PM + '</td><td>' + x.H04PM + '</td><td>' + x.H06PM + '</td><td>' + x.H08PM + '</td><td>' + x.H10PM + '</td><td>' + x.H12AM + '</td><td>' + x.H02AM + '</td><td>' + x.H04AM + '</td><td>' + x.H06AM + '</td><td>' + x.H08AM + '</td><td>' + x.TotalCompleted + '</td><td>' + workedDuration(x.TotalDurationMinutes) + '</td></tr>'; }).join('') : '<tr><td colspan="16" class="olt-empty">No completed orders found for this production date.</td></tr>'; }).catch(showError); }
function loadReProject() { reDeal.disabled = true; reProcess.disabled = true; reFromUser.disabled = true; reToUser.disabled = true; reRows.innerHTML = '<tr><td colspan="9" class="olt-empty">Select project, deal, process and current user.</td></tr>'; if (!reProject.value) return; Promise.all([OLT.call(page, 'GetDeals', { projectId: +reProject.value }), OLT.call(page, 'GetUsers', { projectId: +reProject.value })]).then(function (r) { OLT.options(reDeal, r[0], ['DealNo', 'DealNumber', 'Deal'], ['DealNo', 'DealNumber', 'Deal'], 'Select deal'); reDeal.disabled = false; reAllUsers = r[1] || []; renderReTargets(); }).catch(showError); }
function enableReProcess() { reProcess.disabled = true; reFromUser.disabled = true; reRows.innerHTML = '<tr><td colspan="9" class="olt-empty">Select process and current user.</td></tr>'; if (!reDeal.value) return; OLT.call(page, 'GetFlow', { projectId: +reProject.value, dealNumber: reDeal.value }).then(function (r) { OLT.options(reProcess, r, ['ProcessID'], ['ProcessName'], 'Select process'); reProcess.disabled = false; }).catch(showError); }
function loadReUsers() { reFromUser.disabled = true; if (!reProject.value || !reDeal.value || !reProcess.value) return; OLT.call(page, 'GetReallocationUsers', { projectId: +reProject.value, dealNumber: reDeal.value, processId: +reProcess.value }).then(function (r) { OLT.options(reFromUser, r, ['UserID'], ['UserName'], 'Select current user'); reFromUser.disabled = false; renderReTargets(); }).catch(showError); }
function renderReTargets() { reToUser.innerHTML = '<option value="">Select new user</option>'; reAllUsers.filter(function (x) { return String(x.UserID) !== String(reFromUser.value); }).forEach(function (x) { var o = document.createElement('option'); o.value = x.UserID; o.textContent = x.UserName + ' (' + x.ActiveCount + ' active)'; reToUser.appendChild(o); }); reToUser.disabled = !reProject.value; }
function loadReOrders() { if (!reFromUser.value) return; OLT.call(page, 'GetReallocationOrders', { projectId: +reProject.value, dealNumber: reDeal.value, processId: +reProcess.value, fromUserId: +reFromUser.value }).then(function (r) { reCurrentOrders = r || []; reRows.innerHTML = reCurrentOrders.length ? reCurrentOrders.map(function (x) { return '<tr><td><input type="checkbox" class="mgr-select re-check" value="' + x.AssignmentID + '" onchange="limitReSelection(this)"/></td><td>' + esc(x.ProjectName) + '</td><td>' + esc(x.DealNumber) + '</td><td>' + esc(x.ProcessName) + '</td><td>' + esc(x.LoanNumber) + '</td><td>' + esc(x.UserName) + '</td><td>' + esc(x.AssignmentStatus) + '</td><td>' + esc(x.LastRemark) + '</td><td>' + fmt(x.AssignedDate) + '</td></tr>'; }).join('') : '<tr><td colspan="9" class="olt-empty">No allocated orders found for this user.</td></tr>'; }).catch(showError); }
function limitReSelection(changed) { if (document.querySelectorAll('.re-check:checked').length > 2) { changed.checked = false; OLT.alert('Select a maximum of two orders.', true); } }

function reallocateSelected() {
    var ids = [].slice.call(document.querySelectorAll('.re-check:checked')).map(function (x) { return +x.value; });

    if (!reFromUser.value) {

        OLT.alert('Please select Current User.', true); return;
    }

    if (!reToUser.value) {
        OLT.alert('Please select New User.', true); return;
    }

    if (!reRemark.value.trim()) {
        OLT.alert('Re-allocation remark is required.', true); return;
    }

    if (!ids.length || ids.length > 2) { OLT.alert('Select one or two orders.', true); return; }

    var hasInProcess = reCurrentOrders.some(function (order) {
        return ids.indexOf(+order.AssignmentID) >= 0 && order.AssignmentStatus === 'In Process';
    });

    if (hasInProcess && !window.confirm('Are you sure you want to reallocate this loan? This loan is currently In-Process.')) {
        return;
    }

    OLT.call(page, 'ReallocateOrders', { projectId: +reProject.value, fromUserId: +reFromUser.value, toUserId: +reToUser.value, assignmentIds: ids, remark: reRemark.value, confirmInProcess: hasInProcess }).then(function (r) {

        if (!r || r.Success !== true) {
            OLT.alert(r && r.Message ? r.Message : 'Re-allocation failed.', true); return;
        }

        OLT.alert(r.Message); reRemark.value = ''; loadReUsers(); reRows.innerHTML = '<tr><td colspan="9" class="olt-empty">Select current user to refresh orders.</td></tr>';
    }).catch(showError);
}


function exportTable(tableId, fileName) { var rows = [].slice.call(document.querySelectorAll('#' + tableId + ' tr')), csv = rows.map(function (row) { return [].slice.call(row.querySelectorAll('th,td')).map(function (cell) { return '"' + cell.textContent.trim().replace(/"/g, '""') + '"'; }).join(','); }).join('\r\n'), blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' }), a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = fileName; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(a.href); }
function fmtDate(v) { var n = parseInt(String(v || '').replace(/\D/g, ''), 10); return n ? new Date(n).toLocaleDateString() : ''; }
function fmtTime(v) { var n = parseInt(String(v || '').replace(/\D/g, ''), 10); return n ? new Date(n).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : ''; }
function duration(v) { var s = Math.max(0, +v || 0), d = Math.floor(s / 86400); s %= 86400; var h = Math.floor(s / 3600); s %= 3600; var m = Math.floor(s / 60); return (d ? d + 'd ' : '') + String(h).padStart(2, '0') + ':' + String(m).padStart(2, '0'); } function workedDuration(minutes) { minutes = Math.max(0, +minutes || 0); return Math.floor(minutes / 60) + ':' + String(Math.floor(minutes % 60)).padStart(2, '0'); } function fmt(v) { var n = parseInt(String(v || '').replace(/\D/g, ''), 10); return n ? new Date(n).toLocaleString() : ''; } function esc(v) { return OLT.esc(v); } function showError() { OLT.alert('The report could not be loaded. Please try again.', true); }
