var pc_confirmCallback=null;
function pc_showMessage(title,message){$('#pcMessageTitle').text(title||'Message');$('#pcMessageBody').text(message||'');$('#pcMessageModal').modal('show');}
function pc_showConfirm(title,message,callback){$('#pcConfirmTitle').text(title||'Confirmation');$('#pcConfirmMessage').text(message||'');pc_confirmCallback=callback;$('#pcConfirmModal').modal('show');}
$(document).on('click','#pcConfirmYes',function(){$('#pcConfirmModal').modal('hide');var cb=pc_confirmCallback;pc_confirmCallback=null;if(typeof cb==='function')cb();});
function pc_validate(){if(!$('#pc_Employee').val()){pc_showMessage('Validation','Please select Employee.');return false;}if(!$('#pc_Category').val()){pc_showMessage('Validation','Please select Category.');return false;}if(!$('#pc_RequestDate').val()||!$('#pc_RequiredDate').val()){pc_showMessage('Validation','Request Date and Required Date are mandatory.');return false;}if($('#pc_RequiredDate').val()<$('#pc_RequestDate').val()){pc_showMessage('Validation','Required Date cannot be before Request Date.');return false;}if(!$('#pc_Purpose').val().trim()){pc_showMessage('Validation','Purpose is mandatory.');return false;}if(Number($('#pc_Amount').val())<=0){pc_showMessage('Validation','Amount must be greater than zero.');return false;}return true;}
function pc_confirmSubmit(){if(!pc_validate())return;pc_showConfirm('Submit Request','Are you sure you want to submit this petty cash request?',function(){pc_saveRequest(true);});}
function pc_saveRequest(submit){if(!pc_validate())return;var payload={requestId:Number($('#pc_RequestID').val()||0),employeeId:Number($('#pc_Employee').val()),categoryId:Number($('#pc_Category').val()),requestDate:$('#pc_RequestDate').val(),requiredDate:$('#pc_RequiredDate').val(),purpose:$('#pc_Purpose').val().trim(),amount:Number($('#pc_Amount').val()),priority:$('#pc_Priority').val(),remark:$('#pc_Remark').val().trim(),submit:submit};$.ajax({type:'POST',url:'PettyCashRequest.aspx/SaveRequest',data:JSON.stringify(payload),contentType:'application/json; charset=utf-8',dataType:'json',success:function(){pc_showMessage('Success',submit?'Request submitted successfully.':'Draft saved successfully.');pc_bindRequests();},error:function(x){pc_showMessage('Error',pc_error(x));}});}
function pc_error(x){try{return JSON.parse(x.responseText).Message||'Unable to process request.';}catch(e){return 'Unable to process request.';}}
function pc_bindCategories(){$.ajax({type:'POST',url:'PettyCashRequest.aspx/GetCategories',data:'{}',contentType:'application/json; charset=utf-8',dataType:'json',success:function(r){var a=JSON.parse(r.d||'[]'),$s=$('#pc_Category').empty().append('<option value="">Select</option>');$.each(a,function(_,v){$s.append($('<option/>').val(v.CategoryID).text(v.CategoryName));});}});}
function pc_bindRequests(){$.ajax({type:'POST',url:'PettyCashRequest.aspx/GetRequests',data:'{}',contentType:'application/json; charset=utf-8',dataType:'json',success:function(r){var a=JSON.parse(r.d||'[]');if($.fn.DataTable){$('#pc_RequestTable').DataTable({destroy:true,data:a,scrollX:true,ordering:false,pageLength:35,columns:[{data:'RequestNo'},{data:'RequestDate'},{data:'Purpose'},{data:'RequestedAmount'},{data:'Status'}]});}}});}
$(function(){pc_bindCategories();pc_bindRequests();/* Bind #pc_Employee with your existing employee WebMethod/dropdown source. */});
