<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EmployeeITDetails.aspx.cs" Inherits="WebPortal.Assets.EmployeeITDetails" MasterPageFile="~/Assets/Admin.Master" %>
<asp:Content ID="HeadContent" ContentPlaceHolderID="head" runat="server"><link href="asset-common.css" rel="stylesheet" /></asp:Content>
<asp:Content ID="MainContent" ContentPlaceHolderID="ContentPlaceHolder1" runat="server"><div class="asset-page"><div class="asset-hero"><h2>Employee IT Details</h2><small>Assets / Employee IT Details</small></div>
<div class="erp-panel"><div class="erp-panel-title">Employee</div><div class="erp-panel-body"><div class="row"><div class="col-md-6 form-group"><label class="required">Employee Code - Name</label><select id="employee" class="form-control"><option value="">-- Select Employee --</option></select></div><div class="col-md-3 form-group" style="padding-top:28px"><a href="EmployeeITFieldMaster.aspx" class="btn btn-secondary"><i class="fa fa-cogs"></i> Manage Additional Fields</a></div></div></div></div>
<div class="erp-panel"><div class="erp-panel-title">IT Access and Account Details</div><div class="erp-panel-body"><div id="fields" class="row entry-form"><div class="col-md-12 text-muted">Select an employee to load IT details.</div></div><button id="saveButton" class="btn btn-primary" style="display:none" onclick="saveDetails();return false;">Save IT Details</button></div></div>
<div class="erp-panel"><div class="erp-panel-title">Assets Allocated to Employee</div><div class="erp-panel-body"><table id="assets" class="table table-bordered table-sm"></table></div></div></div>
<script src="asset-common.js"></script><script>
var profileFields=[];
function control(f){var id='it_'+f.FieldID,disabled=f.IsReadOnly?' disabled':'';if(f.FieldType==='YesNo')return '<select id="'+id+'" data-id="'+f.FieldID+'" data-code="'+AssetUI.escape(f.FieldCode)+'" class="form-control it-field"'+disabled+'><option value="">-- Select --</option><option value="Yes">Yes</option><option value="No">No</option></select>';if(f.FieldType==='LongText')return '<textarea id="'+id+'" data-id="'+f.FieldID+'" data-code="'+AssetUI.escape(f.FieldCode)+'" class="form-control it-field" rows="3"'+disabled+'></textarea>';return '<input id="'+id+'" data-id="'+f.FieldID+'" data-code="'+AssetUI.escape(f.FieldCode)+'" class="form-control it-field"'+disabled+' />';}
function renderFields(rows){profileFields=rows||[];var html=profileFields.map(function(f){return '<div class="col-md-'+(f.FieldType==='LongText'?12:6)+' form-group field-wrap" data-dep="'+AssetUI.escape(f.DependsOnFieldCode||'')+'" data-depvalue="'+AssetUI.escape(f.DependsOnValue||'')+'"><label class="'+(f.IsRequired?'required':'')+'">'+AssetUI.escape(f.FieldLabel)+(f.IsReadOnly?' <small>(from Employee Master)</small>':'')+'</label>'+control(f)+'</div>';}).join('');$('#fields').html(html||'<div class="col-md-12 text-muted">No IT fields are configured.</div>');profileFields.forEach(function(f){$('#it_'+f.FieldID).val(f.FieldValue||'');});applyDependencies();$('#saveButton').toggle(profileFields.length>0);}
function applyDependencies(){$('.field-wrap[data-dep!=""]').each(function(){var w=$(this),source=$('.it-field[data-code="'+w.data('dep')+'"]');w.toggle(String(source.val()||'')===String(w.data('depvalue')));});}
function loadEmployee(){var id=+$('#employee').val();if(!id){renderFields([]);loadAssets([]);return;}AssetUI.post('EmployeeITDetails.aspx/Profile',{employeeID:id},renderFields);AssetUI.post('EmployeeITDetails.aspx/Assets',{employeeID:id},loadAssets);}
function loadAssets(r){AssetUI.table('#assets',r||[],[{data:'AssetTagNumber',title:'Asset Tag'},{data:'AssetTypeName',title:'Asset Type'},{data:'ShiftName',title:'Shift'},{data:'BranchName',title:'Branch'},{data:'AllocationDate',title:'Allocated On'},{data:'AssetStatusName',title:'Asset Status'}],[{text:'View',fn:'viewAsset',id:'AssetID'}]);}
function saveDetails(){var employeeID=+$('#employee').val();if(!employeeID){AssetUI.message('Select an employee.','error');return;}var ok=true,values=[];profileFields.forEach(function(f){if(f.IsReadOnly)return;var el=$('#it_'+f.FieldID),visible=el.closest('.field-wrap').is(':visible'),value=el.val()||'';if(visible&&f.IsRequired&&!$.trim(value)){el.addClass('is-invalid');ok=false;}values.push({FieldID:+f.FieldID,FieldValue:value});});if(!ok){AssetUI.message('Complete all required IT details.','error');return;}AssetUI.post('EmployeeITDetails.aspx/Save',{x:{EmployeeID:employeeID,Values:values}},function(){loadEmployee();});}
function viewAsset(id){location.href='AssetDetails.aspx?id='+id;}$(document).on('change','#employee',loadEmployee).on('change','.it-field',applyDependencies);$(function(){AssetUI.post('EmployeeITDetails.aspx/Lookup',{type:'Employee',parentID:null},function(r){AssetUI.fill('#employee',r,'ID','Name');});});
</script></asp:Content>
