<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="QuotationComparison.aspx.cs" Inherits="WebPortal.Assets.QuotationComparison" MasterPageFile="~/Assets/Admin.Master" %>
<asp:Content ID="HeadContent" ContentPlaceHolderID="head" runat="server"><link href="asset-common.css" rel="stylesheet" /></asp:Content>
<asp:Content ID="MainContent" ContentPlaceHolderID="ContentPlaceHolder1" runat="server"><div class="asset-page"><div class="asset-hero"><h2>Quotation Comparison</h2><small>Assets / Procurement / Quotation Comparison</small></div><div class="erp-panel"><div class="erp-panel-title">Select Purchase Request</div><div class="erp-panel-body"><div class="row"><div class="col-md-5 form-group"><label class="required">Purchase Request</label><select id="request" class="form-control"><option value="">-- Select --</option></select></div></div><button class="btn btn-primary" onclick="load();return false;">Compare Quotations</button></div></div><div id="selectedSummary" class="asset-message success" style="display:none"></div><div class="erp-panel"><div class="erp-panel-title">Commercial Comparison</div><div class="erp-panel-body"><div style="position:relative"><table id="grid" class="table table-bordered table-sm"></table></div></div></div><div id="selectionPanel" class="erp-panel" style="display:none"><div class="erp-panel-title">Final Quotation Selection</div><div class="erp-panel-body"><input id="selectedQuotation" type="hidden"/><div class="row"><div class="col-md-8 form-group"><label>Selected Quotation</label><div id="selectionDescription" class="form-control"></div></div><div class="col-md-8 form-group"><label class="required">Selection Reason / Commercial Justification</label><textarea id="selectionReason" class="form-control" rows="3" placeholder="Record why this vendor and quotation were selected"></textarea></div></div><button class="btn btn-success" onclick="confirmSelection();return false;">Confirm Final Selection</button> <button class="btn btn-secondary" onclick="cancelSelection();return false;">Cancel</button></div></div><script>
var quotationRows=[];
function look(){AssetUI.post('QuotationComparison.aspx/Lookup',{type:'PurchaseRequest',parentID:null},function(rows){AssetUI.fill('#request',rows,'ID','Name');});}
function load(){var requestID=+$('#request').val();if(!requestID){AssetUI.message('Select a purchase request to compare quotations.','error');return;}AssetUI.post('QuotationComparison.aspx/List',{requestID:requestID},function(rows){quotationRows=rows||[];var columns=[{data:'VendorName',title:'Vendor'},{data:'QuotationNumber',title:'Quotation No.'},{data:'TotalQuotationValue',title:'Total Value'},{data:'DeliveryPeriod',title:'Delivery'},{data:'PaymentTerms',title:'Payment Terms'},{data:'WarrantyTerms',title:'Warranty'},{data:'ValidUntilDate',title:'Valid Until'},{data:'IsSelected',title:'Final Selection'}];AssetUI.table('#grid',quotationRows,columns,[{text:'Final Select',fn:'prepareSelection',id:'QuotationID'},{text:'View',fn:'view',id:'QuotationID'}]);var selected=null;$.each(quotationRows,function(_,row){if(row.IsSelected)selected=row;});if(selected){$('#selectedSummary').html('<strong>Final selection:</strong> '+$('<div>').text(selected.VendorName+' — '+selected.QuotationNumber+' — '+Number(selected.TotalQuotationValue||0).toLocaleString('en-IN',{minimumFractionDigits:2})).html()+(selected.SelectionReason?' | '+$('<div>').text(selected.SelectionReason).html():'')).show();}else{$('#selectedSummary').hide();}cancelSelection();});}
function prepareSelection(id,row){$('#selectedQuotation').val(id);$('#selectionDescription').text((row.VendorName||'')+' — '+(row.QuotationNumber||'')+' — '+Number(row.TotalQuotationValue||0).toLocaleString('en-IN',{minimumFractionDigits:2}));$('#selectionReason').val(row.SelectionReason||'');$('#selectionPanel').slideDown();$('#selectionReason').focus();}
function confirmSelection(){var id=+$('#selectedQuotation').val(),requestID=+$('#request').val(),reason=$.trim($('#selectionReason').val());if(!id||!requestID){AssetUI.message('Select a quotation first.','error');return;}if(!reason){$('#selectionReason').addClass('is-invalid').focus();AssetUI.message('Selection reason is required.','error');return;}if(!window.confirm('Confirm this quotation as the final commercial selection?'))return;AssetUI.post('QuotationComparison.aspx/Select',{id:id,requestID:requestID,reason:reason},load);}
function cancelSelection(){$('#selectionPanel').hide();$('#selectedQuotation').val('');$('#selectionReason').val('').removeClass('is-invalid');}
function view(id){location.href='VendorQuotation.aspx?id='+id;}
$(look);
</script></div><script src="asset-common.js"></script></asp:Content>
