<%@ Page Title="PM Order Allocation" Language="C#" MasterPageFile="~/Production/Production.Master" AutoEventWireup="true" CodeBehind="ManagerAllocation.aspx.cs" Inherits="WebPortal.TrackingSheet.ManagerAllocationPage" %>
<asp:Content ID="Head" ContentPlaceHolderID="head" runat="server"><link rel="stylesheet" href="OLTracking.css" /><style>.pma-loans{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:10px}.pma-loan{display:flex;gap:8px;align-items:center;padding:10px;border:1px solid #d7e2ee;border-radius:6px}.pma-loan input{width:17px;height:17px}.pma-user-note{margin-top:6px;color:#64748b;font-size:12px}@media(max-width:800px){.pma-loans{grid-template-columns:1fr}}</style></asp:Content>
<asp:Content ID="Body" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="olt-page"><div class="olt-hero"><div><h2>PM Order Allocation</h2><p>Allocate up to two eligible orders to a selected project user.</p></div><div class="olt-links"><a href="TrackingSheet.aspx">Tracking sheet</a><a href="ManagerDashboard.aspx">Manager dashboard</a></div></div><div id="oltAlert" class="olt-alert"></div>
<div class="olt-card"><div class="olt-card-head">Allocation details</div><div class="olt-card-body"><div class="olt-form">
<div class="olt-field wide"><label>Project #</label><select id="pmaProject"><option value="">Select project</option></select></div>
<div class="olt-field wide"><label>Deal #</label><select id="pmaDeal" disabled><option value="">Select project first</option></select></div>
<div class="olt-field wide"><label>Process</label><select id="pmaProcess" disabled><option value="">Select deal first</option></select></div>
<div class="olt-field wide"><label>User</label><select id="pmaUser" disabled><option value="">Select project first</option></select><div id="pmaUserNote" class="pma-user-note"></div></div>
</div><div class="ots-note">Select a maximum of two orders. The selected user can have no more than two Pending/In Process orders after allocation.</div><div id="pmaLoans" class="pma-loans"><div class="olt-empty">Select project, deal and process.</div></div><div class="olt-actions" style="margin-top:14px"><button type="button" class="olt-btn" onclick="allocateSelected()">Allocate Selected Orders</button></div></div></div></div>
<script src="OLTracking.js"></script><script>
var page='ManagerAllocation.aspx',users=[];document.addEventListener('DOMContentLoaded',function(){OLT.call(page,'GetProjects').then(function(r){OLT.options(pmaProject,r,['ProjectID'],['ProjectName'],'Select project');});pmaProject.onchange=loadProjectData;pmaDeal.onchange=enableProcess;pmaProcess.onchange=loadLoans;pmaUser.onchange=showUserCount;});
function loadProjectData(){pmaDeal.disabled=true;pmaProcess.disabled=true;pmaUser.disabled=true;pmaLoans.innerHTML='<div class="olt-empty">Loading...</div>';if(!pmaProject.value)return;Promise.all([OLT.call(page,'GetDeals',{projectId:+pmaProject.value}),OLT.call(page,'GetFlow',{projectId:+pmaProject.value}),OLT.call(page,'GetUsers',{projectId:+pmaProject.value})]).then(function(r){OLT.options(pmaDeal,r[0],['DealNo','DealNumber','Deal'],['DealNo','DealNumber','Deal'],'Select deal');pmaDeal.disabled=false;OLT.options(pmaProcess,r[1],['ProcessID'],['ProcessName'],'Select deal first');users=r[2];pmaUser.innerHTML='<option value="">Select user</option>';users.forEach(function(x){var o=document.createElement('option');o.value=x.UserID;o.textContent=x.UserName+' ('+x.ActiveCount+' active)';pmaUser.appendChild(o);});pmaUser.disabled=false;pmaLoans.innerHTML='<div class="olt-empty">Select deal and process.</div>';}).catch(showError);}
function enableProcess(){pmaProcess.disabled=!pmaDeal.value;pmaProcess.value='';if(pmaProcess.options.length)pmaProcess.options[0].text=pmaDeal.value?'Select process':'Select deal first';pmaLoans.innerHTML='<div class="olt-empty">Select process.</div>';}
function loadLoans(){if(!pmaProject.value||!pmaDeal.value||!pmaProcess.value)return;pmaLoans.innerHTML='<div class="olt-empty">Loading eligible orders...</div>';OLT.call(page,'GetEligibleLoans',{projectId:+pmaProject.value,dealNumber:pmaDeal.value,processId:+pmaProcess.value}).then(function(r){pmaLoans.innerHTML=r.length?r.map(function(x){return'<label class="pma-loan"><input type="checkbox" class="pma-check" value="'+OLT.esc(x.LoanNumber)+'" onchange="limitSelection(this)"/><span>'+OLT.esc(x.LoanNumber)+'</span></label>';}).join(''):'<div class="olt-empty">No eligible orders found.</div>';}).catch(showError);}
function limitSelection(changed){var selected=document.querySelectorAll('.pma-check:checked');if(selected.length>2){changed.checked=false;OLT.alert('Select a maximum of two orders.',true);}}
function showUserCount(){var u=users.filter(function(x){return String(x.UserID)===String(pmaUser.value);})[0];pmaUserNote.textContent=u?u.ActiveCount+' active Pending/In Process order(s).':'';}
function allocateSelected(){var loans=[].slice.call(document.querySelectorAll('.pma-check:checked')).map(function(x){return x.value;});if(!pmaUser.value){OLT.alert('Please select a user.',true);return;}if(!loans.length||loans.length>2){OLT.alert('Select one or two orders.',true);return;}OLT.call(page,'AllocateOrders',{projectId:+pmaProject.value,dealNumber:pmaDeal.value,processId:+pmaProcess.value,targetUserId:+pmaUser.value,loanNumbers:loans}).then(function(r){if(!r||r.Success!==true){OLT.alert(r&&r.Message?r.Message:'Allocation failed.',true);return;}OLT.alert(r.Message);loadProjectData();}).catch(showError);}function showError(){OLT.alert('The requested action could not be completed. Please try again.',true);}
</script></asp:Content>
