using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using WebPortal.App_Code.DAL;

namespace WebPortal.App_Code
{
    public sealed class RnrQuestionInput { public int QuestionID { get; set; } public string Text { get; set; } public string Type { get; set; } public bool Required { get; set; } public int RatingMin { get; set; } public int RatingMax { get; set; } public List<string> Options { get; set; } }
    public sealed class RnrQuestionnaireInput { public int QuestionnaireID { get; set; } public string Title { get; set; } public string Description { get; set; } public string Status { get; set; } public bool IsActive { get; set; } public int Priority { get; set; } public List<RnrQuestionInput> Questions { get; set; } }
    public sealed class RnrAnswerInput { public int QuestionID { get; set; } public string Text { get; set; } public int? Rating { get; set; } public List<int> OptionIDs { get; set; } }

    public sealed class RnrFeedbackRepository
    {
        private SqlConnection Open() { var c = new SqlConnection(SQLHelper.ConnectionString); c.Open(); return c; }
        private static void Add(SqlCommand c, string n, object v) { c.Parameters.AddWithValue(n, v ?? DBNull.Value); }
        private static DataTable Table(SqlCommand c) { var t = new DataTable(); using (var a = new SqlDataAdapter(c)) a.Fill(t); return t; }
        private static DataSet Set(SqlCommand c) { var s = new DataSet(); using (var a = new SqlDataAdapter(c)) a.Fill(s); return s; }
        private static void Audit(SqlConnection c, SqlTransaction t, string entity, long? id, string action, string detail, int actor, string ip)
        { using (var q = new SqlCommand("INSERT dbo.RNR_Audit(EntityType,EntityID,Action,Details,PerformedBy,IPAddress) VALUES(@E,@I,@A,@D,@U,@IP)", c, t)) { Add(q,"@E",entity); Add(q,"@I",id); Add(q,"@A",action); Add(q,"@D",detail); Add(q,"@U",actor); Add(q,"@IP",ip); q.ExecuteNonQuery(); } }

        public DataSet GetAdminData()
        { using (var c=Open()) using(var q=new SqlCommand(@"SELECT QuestionnaireID,Title,Description,Status,IsActive,Priority,CreatedDate,PublishedDate FROM dbo.RNR_Questionnaire ORDER BY CreatedDate DESC;
SELECT Value,Text FROM (VALUES('Underwriting','Underwriting'),('Support','Support'),('Non-DD','Non-DD')) d(Value,Text);
SELECT BranchID Value,BranchName Text FROM dbo.Branch where isDelete=0 ORDER BY BranchName;
SELECT DepartmentID Value,DepartmentName Text FROM dbo.Department ORDER BY DepartmentName;", c)) return Set(q); }

        public DataSet GetQuestionnaire(int id)
        { using(var c=Open()) using(var q=new SqlCommand(@"SELECT * FROM dbo.RNR_Questionnaire WHERE QuestionnaireID=@ID;
SELECT * FROM dbo.RNR_Question WHERE QuestionnaireID=@ID ORDER BY SortOrder;
SELECT o.* FROM dbo.RNR_Option o JOIN dbo.RNR_Question x ON x.QuestionID=o.QuestionID WHERE x.QuestionnaireID=@ID ORDER BY x.SortOrder,o.SortOrder;",c)){Add(q,"@ID",id);return Set(q);} }

        public int SaveQuestionnaire(RnrQuestionnaireInput input,int actor,string ip)
        {
            if(input==null || String.IsNullOrWhiteSpace(input.Title) || input.Questions==null || input.Questions.Count==0) throw new ArgumentException("Title and at least one question are required.");
            string[] types={"Text","SingleChoice","MultipleChoice","YesNo","Rating"};
            if(input.Questions.Any(x=>String.IsNullOrWhiteSpace(x.Text)||!types.Contains(x.Type))) throw new ArgumentException("Every question needs valid text and type.");
            if(input.Questions.Any(x=>(x.Type=="SingleChoice"||x.Type=="MultipleChoice")&&(x.Options==null||x.Options.Count<2))) throw new ArgumentException("Choice questions need at least two options.");
            using(var c=Open()) using(var t=c.BeginTransaction(IsolationLevel.Serializable)) try {
                int id=input.QuestionnaireID;
                if(id>0){
                    using(var guard=new SqlCommand("IF EXISTS(SELECT 1 FROM dbo.RNR_Response r JOIN dbo.RNR_Assignment a ON a.AssignmentID=r.AssignmentID WHERE a.QuestionnaireID=@ID) THROW 50001,'Published questionnaires with responses cannot be structurally edited. Create a new questionnaire.',1;",c,t)){Add(guard,"@ID",id);guard.ExecuteNonQuery();}
                    using(var q=new SqlCommand("UPDATE dbo.RNR_Questionnaire SET Title=@T,Description=@D,Status=@S,IsActive=@A,Priority=@P,ModifiedBy=@U,ModifiedDate=SYSDATETIME(),PublishedBy=CASE WHEN Status='Draft' AND @S='Published' THEN @U ELSE PublishedBy END,PublishedDate=CASE WHEN Status='Draft' AND @S='Published' THEN SYSDATETIME() ELSE PublishedDate END WHERE QuestionnaireID=@ID; DELETE dbo.RNR_Question WHERE QuestionnaireID=@ID;",c,t)){Add(q,"@T",input.Title.Trim());Add(q,"@D",input.Description);Add(q,"@S",input.Status=="Published"?"Published":"Draft");Add(q,"@A",input.IsActive);Add(q,"@P",input.Priority);Add(q,"@U",actor);Add(q,"@ID",id);q.ExecuteNonQuery();}
                } else using(var q=new SqlCommand("INSERT dbo.RNR_Questionnaire(Title,Description,Status,IsActive,Priority,CreatedBy,PublishedBy,PublishedDate) VALUES(@T,@D,@S,@A,@P,@U,CASE WHEN @S='Published' THEN @U END,CASE WHEN @S='Published' THEN SYSDATETIME() END);SELECT CONVERT(int,SCOPE_IDENTITY());",c,t)){Add(q,"@T",input.Title.Trim());Add(q,"@D",input.Description);Add(q,"@S",input.Status=="Published"?"Published":"Draft");Add(q,"@A",input.IsActive);Add(q,"@P",input.Priority);Add(q,"@U",actor);id=Convert.ToInt32(q.ExecuteScalar());}
                int order=0; foreach(var x in input.Questions){int qid;using(var q=new SqlCommand("INSERT dbo.RNR_Question(QuestionnaireID,QuestionText,QuestionType,IsRequired,SortOrder,RatingMin,RatingMax) VALUES(@Q,@T,@Y,@R,@O,@Min,@Max);SELECT CONVERT(int,SCOPE_IDENTITY());",c,t)){Add(q,"@Q",id);Add(q,"@T",x.Text.Trim());Add(q,"@Y",x.Type);Add(q,"@R",x.Required);Add(q,"@O",++order);Add(q,"@Min",x.Type=="Rating"?(object)Math.Max(1,x.RatingMin):DBNull.Value);Add(q,"@Max",x.Type=="Rating"?(object)Math.Min(10,Math.Max(x.RatingMin+1,x.RatingMax)):DBNull.Value);qid=Convert.ToInt32(q.ExecuteScalar());} if(x.Options!=null){int oo=0;foreach(string option in x.Options.Where(o=>!String.IsNullOrWhiteSpace(o))){using(var q=new SqlCommand("INSERT dbo.RNR_Option(QuestionID,OptionText,SortOrder) VALUES(@Q,@T,@O)",c,t)){Add(q,"@Q",qid);Add(q,"@T",option.Trim());Add(q,"@O",++oo);q.ExecuteNonQuery();}}}}
                Audit(c,t,"Questionnaire",id,input.QuestionnaireID==0?"Create":"Update",input.Status,actor,ip);t.Commit();return id;
            } catch {t.Rollback();throw;}
        }

        public void SetActive(int questionnaireId,bool active,int actor,string ip)
        { using(var c=Open()) using(var t=c.BeginTransaction()) try { using(var q=new SqlCommand("UPDATE dbo.RNR_Questionnaire SET IsActive=@A,ModifiedBy=@U,ModifiedDate=SYSDATETIME() WHERE QuestionnaireID=@ID; IF @@ROWCOUNT=0 THROW 50004,'Questionnaire not found.',1;",c,t)){Add(q,"@A",active);Add(q,"@U",actor);Add(q,"@ID",questionnaireId);q.ExecuteNonQuery();} Audit(c,t,"Questionnaire",questionnaireId,active?"Activate":"Deactivate",null,actor,ip);t.Commit(); }catch{t.Rollback();throw;} }

        public DataTable Employees(string domainGroup,int location,int department)
        { using(var c=Open()) using(var q=new SqlCommand(@"SELECT e.EmployeeID,e.Code EmployeeCode,LTRIM(RTRIM(ISNULL(e.FirstName,'')+' '+ISNULL(e.lastName,''))) EmployeeName,d.DomainName,b.BranchName Location,dep.DepartmentName Department FROM dbo.EmployeeInfo e LEFT JOIN dbo.Domain d ON d.DomainId=e.Domain LEFT JOIN dbo.Branch b ON b.BranchID=e.WorkingBranch LEFT JOIN dbo.Department dep ON dep.DepartmentID=e.Department WHERE COmpany=1 and ISNULL(e.IsDelete,0)=0 AND (@G='' OR (@G='Underwriting' AND d.DomainName LIKE '%Underwriting%') OR (@G='Support' AND d.DomainName='Support') OR (@G='Non-DD' AND ISNULL(d.DomainName,'') NOT LIKE '%Underwriting%' AND ISNULL(d.DomainName,'')<>'Support')) AND (@L=0 OR e.WorkingBranch=@L) AND (@DEP=0 OR e.Department=@DEP) ORDER BY EmployeeName",c)){Add(q,"@G",domainGroup??"");Add(q,"@L",location);Add(q,"@DEP",department);return Table(q);} }

        public int Assign(int questionnaireId,int surveyYear,int quarterMask,IEnumerable<int> employees,int actor,string ip)
        { var ids=(employees??Enumerable.Empty<int>()).Distinct().ToList(); if(ids.Count==0) throw new ArgumentException("Select at least one employee.");if(surveyYear<2000||surveyYear>2100)throw new ArgumentException("Select a valid year.");if(quarterMask<1||quarterMask>15)throw new ArgumentException("Select at least one quarter."); using(var c=Open()) using(var t=c.BeginTransaction(IsolationLevel.Serializable)) try {int count=0; foreach(int employee in ids) using(var q=new SqlCommand(@"IF NOT EXISTS(SELECT 1 FROM dbo.RNR_Assignment WITH(UPDLOCK,HOLDLOCK) WHERE QuestionnaireID=@Q AND EmployeeID=@E AND SurveyYear=@Y AND IsActive=1 AND (QuarterMask & @M)<>0) BEGIN INSERT dbo.RNR_Assignment(QuestionnaireID,EmployeeID,SurveyYear,QuarterMask,AssignedBy) SELECT @Q,@E,@Y,@M,@U WHERE EXISTS(SELECT 1 FROM dbo.RNR_Questionnaire WHERE QuestionnaireID=@Q AND Status='Published' AND IsActive=1); SELECT @@ROWCOUNT; END ELSE SELECT 0;",c,t)){Add(q,"@Q",questionnaireId);Add(q,"@E",employee);Add(q,"@Y",surveyYear);Add(q,"@M",quarterMask);Add(q,"@U",actor);count+=Convert.ToInt32(q.ExecuteScalar());} Audit(c,t,"Assignment",questionnaireId,"Publish",surveyYear+"/mask "+quarterMask+": assigned "+count+" employee(s)",actor,ip);t.Commit();return count;}catch{t.Rollback();throw;} }

        public long PendingAssignment(int employeeId)
        { using(var c=Open()) using(var q=new SqlCommand(@"SELECT TOP 1 a.AssignmentID FROM dbo.RNR_Assignment a JOIN dbo.RNR_Questionnaire q ON q.QuestionnaireID=a.QuestionnaireID LEFT JOIN dbo.RNR_Response r ON r.AssignmentID=a.AssignmentID WHERE a.EmployeeID=@E AND a.IsActive=1 AND a.IsMandatory=1 AND q.IsActive=1 AND q.Status='Published' AND r.ResponseID IS NULL ORDER BY q.Priority DESC,a.AssignedDate,a.AssignmentID",c)){Add(q,"@E",employeeId);return Convert.ToInt64(q.ExecuteScalar()??0);} }

        public DataSet Form(long assignmentId,int employeeId)
        { using(var c=Open()) using(var q=new SqlCommand(@"SELECT a.AssignmentID,q.QuestionnaireID,q.Title,q.Description,a.SurveyYear,STUFF(CASE WHEN a.QuarterMask&1=1 THEN ', January - March' ELSE '' END+CASE WHEN a.QuarterMask&2=2 THEN ', April - June' ELSE '' END+CASE WHEN a.QuarterMask&4=4 THEN ', July - September' ELSE '' END+CASE WHEN a.QuarterMask&8=8 THEN ', October - December' ELSE '' END,1,2,'') Quarter,e.Code EmployeeCode,LTRIM(RTRIM(ISNULL(e.FirstName,'')+' '+ISNULL(e.lastName,''))) EmployeeName,b.BranchName Location FROM dbo.RNR_Assignment a JOIN dbo.RNR_Questionnaire q ON q.QuestionnaireID=a.QuestionnaireID JOIN dbo.EmployeeInfo e ON e.EmployeeID=a.EmployeeID LEFT JOIN dbo.Branch b ON b.BranchID=e.WorkingBranch LEFT JOIN dbo.RNR_Response r ON r.AssignmentID=a.AssignmentID WHERE a.AssignmentID=@A AND a.EmployeeID=@E AND a.IsActive=1 AND q.IsActive=1 AND q.Status='Published' AND r.ResponseID IS NULL;
SELECT x.QuestionID,x.QuestionText,x.QuestionType,x.IsRequired,x.SortOrder,x.RatingMin,x.RatingMax FROM dbo.RNR_Question x JOIN dbo.RNR_Assignment a ON a.QuestionnaireID=x.QuestionnaireID WHERE a.AssignmentID=@A AND a.EmployeeID=@E ORDER BY x.SortOrder;
SELECT o.OptionID,o.QuestionID,o.OptionText,o.SortOrder FROM dbo.RNR_Option o JOIN dbo.RNR_Question x ON x.QuestionID=o.QuestionID JOIN dbo.RNR_Assignment a ON a.QuestionnaireID=x.QuestionnaireID WHERE a.AssignmentID=@A AND a.EmployeeID=@E ORDER BY o.SortOrder;",c)){Add(q,"@A",assignmentId);Add(q,"@E",employeeId);return Set(q);} }

        public void Submit(long assignmentId,int employeeId,List<RnrAnswerInput> answers,string ip)
        { answers=answers??new List<RnrAnswerInput>(); using(var c=Open()) using(var t=c.BeginTransaction(IsolationLevel.Serializable)) try {
            DataTable questions;using(var q=new SqlCommand(@"SELECT x.QuestionID,x.QuestionType,x.IsRequired,x.RatingMin,x.RatingMax FROM dbo.RNR_Assignment a JOIN dbo.RNR_Questionnaire n ON n.QuestionnaireID=a.QuestionnaireID JOIN dbo.RNR_Question x ON x.QuestionnaireID=n.QuestionnaireID LEFT JOIN dbo.RNR_Response r ON r.AssignmentID=a.AssignmentID WHERE a.AssignmentID=@A AND a.EmployeeID=@E AND a.IsActive=1 AND n.IsActive=1 AND n.Status='Published' AND r.ResponseID IS NULL",c,t)){Add(q,"@A",assignmentId);Add(q,"@E",employeeId);questions=Table(q);} if(questions.Rows.Count==0) throw new InvalidOperationException("Assignment is invalid or already submitted.");
            foreach(DataRow row in questions.Rows){int id=Convert.ToInt32(row["QuestionID"]);string type=Convert.ToString(row["QuestionType"]);var a=answers.FirstOrDefault(x=>x.QuestionID==id);var selected=a==null||a.OptionIDs==null?new List<int>():a.OptionIDs.Distinct().ToList();bool supplied=a!=null&&((type=="Text"&&!String.IsNullOrWhiteSpace(a.Text))||(type=="YesNo"&&(a.Text=="Yes"||a.Text=="No"))||(type=="Rating"&&a.Rating.HasValue)||((type=="SingleChoice"||type=="MultipleChoice")&&selected.Count>0));if(Convert.ToBoolean(row["IsRequired"])&&!supplied)throw new ArgumentException("Please answer every required question.");if(a!=null&&type=="Rating"&&a.Rating.HasValue&&(a.Rating<Convert.ToInt32(row["RatingMin"])||a.Rating>Convert.ToInt32(row["RatingMax"])))throw new ArgumentException("A rating is outside the allowed range.");if(type=="SingleChoice"&&selected.Count>1)throw new ArgumentException("Select only one answer for a single-choice question.");if(a!=null&&((type!="Rating"&&a.Rating.HasValue)||((type!="SingleChoice"&&type!="MultipleChoice")&&selected.Count>0)||(type!="Text"&&type!="YesNo"&&!String.IsNullOrWhiteSpace(a.Text))))throw new ArgumentException("An answer does not match its question type.");}
            long response;using(var q=new SqlCommand("INSERT dbo.RNR_Response(AssignmentID,EmployeeID) VALUES(@A,@E);SELECT CONVERT(bigint,SCOPE_IDENTITY());",c,t)){Add(q,"@A",assignmentId);Add(q,"@E",employeeId);response=Convert.ToInt64(q.ExecuteScalar());}
            foreach(var a in answers){var options=(a.OptionIDs??new List<int>()).Distinct().ToList();if(options.Count==0)options.Add(0);foreach(int option in options)using(var q=new SqlCommand(@"INSERT dbo.RNR_AnswerDetail(ResponseID,QuestionID,OptionID,TextAnswer,RatingAnswer) SELECT @R,@Q,CASE WHEN @O=0 THEN NULL ELSE o.OptionID END,@T,@V FROM (SELECT 1 n) z LEFT JOIN dbo.RNR_Option o ON o.OptionID=@O AND o.QuestionID=@Q WHERE EXISTS(SELECT 1 FROM dbo.RNR_Question x JOIN dbo.RNR_Assignment s ON s.QuestionnaireID=x.QuestionnaireID WHERE x.QuestionID=@Q AND s.AssignmentID=@A) AND (@O=0 OR o.OptionID IS NOT NULL) AND (@O<>0 OR NULLIF(LTRIM(RTRIM(@T)),'') IS NOT NULL OR @V IS NOT NULL);",c,t)){Add(q,"@R",response);Add(q,"@Q",a.QuestionID);Add(q,"@O",option);Add(q,"@T",a.Text);Add(q,"@V",a.Rating);Add(q,"@A",assignmentId);int written=q.ExecuteNonQuery();if(option!=0&&written!=1)throw new ArgumentException("A selected option is invalid.");}}
            Audit(c,t,"Response",response,"Submit",null,employeeId,ip);t.Commit();
        } catch {t.Rollback();throw;} }

        public DataSet Report(int questionnaire,string domainGroup,int location,int department,int employee,string status,DateTime? from,DateTime? to)
        {using(var c=Open())using(var q=new SqlCommand(@"SELECT a.AssignmentID,e.Code EmployeeID,LTRIM(RTRIM(ISNULL(e.FirstName,'')+' '+ISNULL(e.lastName,''))) EmployeeName,d.DomainName,b.BranchName Location,dep.DepartmentName Department,a.SurveyYear,STUFF(CASE WHEN a.QuarterMask&1=1 THEN ', Jan-Mar' ELSE '' END+CASE WHEN a.QuarterMask&2=2 THEN ', Apr-Jun' ELSE '' END+CASE WHEN a.QuarterMask&4=4 THEN ', Jul-Sep' ELSE '' END+CASE WHEN a.QuarterMask&8=8 THEN ', Oct-Dec' ELSE '' END,1,2,'') Quarter,a.AssignedDate,r.SubmittedDate,CASE WHEN r.ResponseID IS NULL THEN 'Pending' ELSE 'Completed' END Status,q.Title Questionnaire FROM dbo.RNR_Assignment a JOIN dbo.RNR_Questionnaire q ON q.QuestionnaireID=a.QuestionnaireID JOIN dbo.EmployeeInfo e ON e.EmployeeID=a.EmployeeID LEFT JOIN dbo.Domain d ON d.DomainId=e.Domain LEFT JOIN dbo.Branch b ON b.BranchID=e.WorkingBranch LEFT JOIN dbo.Department dep ON dep.DepartmentID=e.Department LEFT JOIN dbo.RNR_Response r ON r.AssignmentID=a.AssignmentID WHERE (@Q=0 OR a.QuestionnaireID=@Q) AND (@G='' OR (@G='Underwriting' AND d.DomainName LIKE '%Underwriting%') OR (@G='Support' AND d.DomainName='Support') OR (@G='Non-DD' AND ISNULL(d.DomainName,'') NOT LIKE '%Underwriting%' AND ISNULL(d.DomainName,'')<>'Support')) AND (@L=0 OR e.WorkingBranch=@L) AND (@DEP=0 OR e.Department=@DEP) AND (@E=0 OR e.EmployeeID=@E) AND (@S='' OR (@S='Pending' AND r.ResponseID IS NULL) OR (@S='Completed' AND r.ResponseID IS NOT NULL)) AND (@F IS NULL OR a.AssignedDate>=@F) AND (@T IS NULL OR a.AssignedDate<DATEADD(day,1,@T)) ORDER BY a.AssignedDate DESC;
SELECT COUNT(*) TotalAssigned,SUM(CASE WHEN r.ResponseID IS NOT NULL THEN 1 ELSE 0 END) Completed,SUM(CASE WHEN r.ResponseID IS NULL THEN 1 ELSE 0 END) Pending FROM dbo.RNR_Assignment a LEFT JOIN dbo.RNR_Response r ON r.AssignmentID=a.AssignmentID JOIN dbo.EmployeeInfo e ON e.EmployeeID=a.EmployeeID LEFT JOIN dbo.Domain d ON d.DomainId=e.Domain WHERE (@Q=0 OR a.QuestionnaireID=@Q) AND (@G='' OR (@G='Underwriting' AND d.DomainName LIKE '%Underwriting%') OR (@G='Support' AND d.DomainName='Support') OR (@G='Non-DD' AND ISNULL(d.DomainName,'') NOT LIKE '%Underwriting%' AND ISNULL(d.DomainName,'')<>'Support')) AND (@L=0 OR e.WorkingBranch=@L) AND (@DEP=0 OR e.Department=@DEP) AND (@E=0 OR e.EmployeeID=@E) AND (@S='' OR (@S='Pending' AND r.ResponseID IS NULL) OR (@S='Completed' AND r.ResponseID IS NOT NULL)) AND (@F IS NULL OR a.AssignedDate>=@F) AND (@T IS NULL OR a.AssignedDate<DATEADD(day,1,@T));",c)){Add(q,"@Q",questionnaire);Add(q,"@G",domainGroup??"");Add(q,"@L",location);Add(q,"@DEP",department);Add(q,"@E",employee);Add(q,"@S",status??"");Add(q,"@F",from);Add(q,"@T",to);return Set(q);} }
        public DataTable Answers(long assignmentId)
        {using(var c=Open())using(var q=new SqlCommand(@"SELECT x.SortOrder,x.QuestionText,x.QuestionType,COALESCE(o.OptionText,CONVERT(nvarchar(20),ad.RatingAnswer),ad.TextAnswer) Answer FROM dbo.RNR_Response r JOIN dbo.RNR_AnswerDetail ad ON ad.ResponseID=r.ResponseID JOIN dbo.RNR_Question x ON x.QuestionID=ad.QuestionID LEFT JOIN dbo.RNR_Option o ON o.OptionID=ad.OptionID WHERE r.AssignmentID=@A ORDER BY x.SortOrder,ad.AnswerDetailID",c)){Add(q,"@A",assignmentId);return Table(q);} }
    }
}
