using System;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace WebPortal.App_Code
{
 public sealed class SoftwareRequestRepository
 {
  private static SqlConnection Open(){var c=new SqlConnection(ConfigurationManager.ConnectionStrings["MainCon"].ConnectionString);c.Open();return c;}
  private static void Add(SqlCommand c,string n,object v){c.Parameters.AddWithValue(n,v??DBNull.Value);}
  private static DataSet Set(SqlCommand c){using(var a=new SqlDataAdapter(c)){var d=new DataSet();a.Fill(d);return d;}}
  private static DataTable Table(SqlCommand c){using(var a=new SqlDataAdapter(c)){var t=new DataTable();a.Fill(t);return t;}}
  private const string ActiveSoftwareEmployee=@"SELECT e.EmployeeID,e.Code+' : '+LTRIM(RTRIM(ISNULL(e.FirstName,'')+' '+ISNULL(e.lastName,''))) DisplayName,e.Code RoleCode FROM dbo.EmployeeInfo e WHERE e.Department=12 AND ISNULL(e.IsDelete,0)=0 AND NOT EXISTS(SELECT 1 FROM dbo.InitiateResignation ir WHERE ir.EmployeeID=e.EmployeeID AND CAST(ir.LastworkingDate AS date)<CAST(GETDATE() AS date))";
  public bool IsTeam(int id){using(var cn=Open())using(var c=new SqlCommand("SELECT COUNT(1) FROM ("+ActiveSoftwareEmployee+") e WHERE e.EmployeeID=@E",cn)){Add(c,"@E",id);return Convert.ToInt32(c.ExecuteScalar())>0;}}
  public DataSet Bootstrap(int id)
  {using(var cn=Open())using(var c=new SqlCommand(@"SELECT RequestTypeID,RequestTypeName FROM dbo.SRM_RequestType WHERE IsActive=1 ORDER BY RequestTypeName;
SELECT ApplicationID,ApplicationName,IsBusinessCritical FROM dbo.SRM_Application WHERE IsActive=1 ORDER BY ApplicationName;
SELECT ModuleID,ApplicationID,ModuleName,IsBusinessCritical FROM dbo.SRM_Module WHERE IsActive=1 ORDER BY ModuleName;
SELECT PriorityCode,PriorityName FROM dbo.SRM_Priority WHERE IsActive=1 ORDER BY SortOrder;
SELECT StatusCode,StatusName FROM dbo.SRM_Status WHERE IsActive=1 ORDER BY SortOrder;
"+ActiveSoftwareEmployee+@" ORDER BY DisplayName;
SELECT CAST(CASE WHEN EXISTS(SELECT 1 FROM ("+ActiveSoftwareEmployee+@") e WHERE e.EmployeeID=@E) THEN 1 ELSE 0 END AS bit) IsSoftwareUser;",cn)){Add(c,"@E",id);return Set(c);}}
  public long Create(Hashtable v)
  {using(var cn=Open())using(var tr=cn.BeginTransaction())try{long id;using(var c=new SqlCommand(@"INSERT dbo.SRM_Request(RequestedBy,RequestedByName,Department,RequestTypeID,ApplicationID,ModuleID,Title,Description,BusinessJustification,RequestedPriority,RequiredByDate,UpdatedBy) VALUES(@By,@ByName,@Department,@Type,@Application,NULLIF(@Module,0),@Title,@Description,@Justification,@Priority,@RequiredBy,@By);SELECT CAST(SCOPE_IDENTITY() AS bigint);",cn,tr)){foreach(DictionaryEntry x in v)Add(c,"@"+x.Key,x.Value);id=Convert.ToInt64(c.ExecuteScalar());}string no="SWR-"+DateTime.Now.Year+"-"+id.ToString("D6");using(var c=new SqlCommand("UPDATE dbo.SRM_Request SET RequestNo=@No WHERE RequestID=@ID;INSERT dbo.SRM_History(RequestID,FieldName,NewValue,Remarks,ChangedBy) VALUES(@ID,'Status','New','Request submitted',@By);",cn,tr)){Add(c,"@No",no);Add(c,"@ID",id);Add(c,"@By",v["By"]);c.ExecuteNonQuery();}tr.Commit();return id;}catch{tr.Rollback();throw;}}
  public DataSet Dashboard(int employeeId,bool canViewAll)
  {using(var cn=Open())using(var c=new SqlCommand(@"SELECT SUM(CASE WHEN StatusCode='New' THEN 1 ELSE 0 END) NewCount,SUM(CASE WHEN StatusCode='In Progress' THEN 1 ELSE 0 END) InProgressCount,SUM(CASE WHEN StatusCode='On Hold' THEN 1 ELSE 0 END) OnHoldCount,SUM(CASE WHEN StatusCode='Testing' THEN 1 ELSE 0 END) TestingCount,SUM(CASE WHEN StatusCode='Completed' THEN 1 ELSE 0 END) CompletedCount FROM dbo.SRM_Request WHERE IsDeleted=0 AND (@All=1 OR RequestedBy=@E);",cn)){Add(c,"@E",employeeId);Add(c,"@All",canViewAll);return Set(c);}}
  public DataTable List(int employeeId,bool canViewAll,string scope,string search,string requester,string department,int applicationId,int moduleId,int developerId,string priority,string status)
  {using(var cn=Open())using(var c=new SqlCommand(@"SELECT r.RequestID,r.RequestNo,r.RequestDate,r.Title RequestTitle,a.ApplicationName,m.ModuleName,r.RequestedByName,r.Department,COALESCE(r.FinalPriority,r.RequestedPriority) Priority,r.AssignedDeveloperName,r.StatusCode,r.ExpectedCompletionDate,r.UpdatedOn,(CASE WHEN a.IsBusinessCritical=1 OR ISNULL(m.IsBusinessCritical,0)=1 THEN 1 ELSE 0 END) IsBusinessCritical FROM dbo.SRM_Request r JOIN dbo.SRM_Application a ON a.ApplicationID=r.ApplicationID LEFT JOIN dbo.SRM_Module m ON m.ModuleID=r.ModuleID WHERE r.IsDeleted=0 AND ((@Scope='Mine' AND r.RequestedBy=@E) OR (@Scope<>'Mine' AND @All=1)) AND (@Search='' OR r.RequestNo LIKE '%'+@Search+'%' OR r.Title LIKE '%'+@Search+'%') AND (@Requester='' OR r.RequestedByName LIKE '%'+@Requester+'%') AND (@Department='' OR r.Department=@Department) AND (@Application=0 OR r.ApplicationID=@Application) AND (@Module=0 OR r.ModuleID=@Module) AND (@Developer=0 OR r.AssignedDeveloperID=@Developer) AND (@Priority='' OR COALESCE(r.FinalPriority,r.RequestedPriority)=@Priority) AND (@Status='' OR r.StatusCode=@Status) ORDER BY CASE WHEN a.IsBusinessCritical=1 OR ISNULL(m.IsBusinessCritical,0)=1 THEN 0 ELSE 1 END,CASE COALESCE(r.FinalPriority,r.RequestedPriority) WHEN 'Critical' THEN 1 WHEN 'High' THEN 2 WHEN 'Medium' THEN 3 ELSE 4 END,ISNULL(r.ExpectedCompletionDate,'99991231'),r.RequestDate;",cn)){Add(c,"@E",employeeId);Add(c,"@All",canViewAll);Add(c,"@Scope",scope??"Mine");Add(c,"@Search",search??"");Add(c,"@Requester",requester??"");Add(c,"@Department",department??"");Add(c,"@Application",applicationId);Add(c,"@Module",moduleId);Add(c,"@Developer",developerId);Add(c,"@Priority",priority??"");Add(c,"@Status",status??"");return Table(c);}}
  public DataSet Detail(long id,int employeeId,bool canViewAll)
  {using(var cn=Open())using(var c=new SqlCommand(@"IF NOT EXISTS(SELECT 1 FROM dbo.SRM_Request WHERE RequestID=@ID AND IsDeleted=0 AND (@All=1 OR RequestedBy=@E)) THROW 50001,'Access denied.',1;
SELECT r.*,t.RequestTypeName,a.ApplicationName,m.ModuleName,(CASE WHEN a.IsBusinessCritical=1 OR ISNULL(m.IsBusinessCritical,0)=1 THEN 1 ELSE 0 END) IsBusinessCritical FROM dbo.SRM_Request r JOIN dbo.SRM_RequestType t ON t.RequestTypeID=r.RequestTypeID JOIN dbo.SRM_Application a ON a.ApplicationID=r.ApplicationID LEFT JOIN dbo.SRM_Module m ON m.ModuleID=r.ModuleID WHERE r.RequestID=@ID;
;WITH Updates AS(SELECT h.RequestID,h.ChangedOn,MAX(CASE WHEN h.FieldName='Assignment' THEN h.NewValue END) DeveloperID,MAX(CASE WHEN h.FieldName IN('Status','Import') THEN h.NewValue END) StatusCode,MAX(CASE WHEN h.FieldName='Completion' THEN h.NewValue END) ExpectedCompletionDate,MAX(CASE WHEN h.FieldName='Update' THEN h.NewValue END) DeveloperRemark,MAX(CASE WHEN h.FieldName='Hold Reason' THEN h.NewValue END) HoldReason,MAX(h.Remarks) Remarks FROM dbo.SRM_History h WHERE h.RequestID=@ID GROUP BY h.RequestID,h.ChangedOn)
SELECT u.ChangedOn,CASE WHEN u.DeveloperID IS NULL THEN NULL ELSE e.Code+' : '+LTRIM(RTRIM(ISNULL(e.FirstName,'')+' '+ISNULL(e.lastName,''))) END AssignedDeveloper,u.StatusCode,u.ExpectedCompletionDate,COALESCE(u.DeveloperRemark,u.Remarks) DeveloperRemark,CASE WHEN u.StatusCode='On Hold' OR NULLIF(u.HoldReason,'') IS NOT NULL THEN u.HoldReason END HoldReason FROM Updates u LEFT JOIN dbo.EmployeeInfo e ON e.EmployeeID=CONVERT(int,u.DeveloperID) ORDER BY u.ChangedOn DESC;
SELECT AttachmentID,OriginalFileName,FileSize,UploadedOn FROM dbo.SRM_Attachment WHERE RequestID=@ID AND IsActive=1 ORDER BY UploadedOn DESC;",cn)){Add(c,"@ID",id);Add(c,"@E",employeeId);Add(c,"@All",canViewAll);return Set(c);}}
  public bool Update(long id,int by,int developerId,string developerName,string finalPriority,string status,DateTime? start,DateTime? completion,string update,string holdReason)
  {using(var cn=Open())using(var tr=cn.BeginTransaction())try{DataRow old;using(var c=new SqlCommand("SELECT * FROM dbo.SRM_Request WHERE RequestID=@ID",cn,tr)){Add(c,"@ID",id);var t=Table(c);if(t.Rows.Count==0)throw new InvalidOperationException("Request not found.");old=t.Rows[0];}bool notify=Convert.ToString(old["StatusCode"])!=status||Convert.ToString(old["LatestUpdate"])!=(update??"");if(status=="On Hold"&&String.IsNullOrWhiteSpace(holdReason))throw new ArgumentException("Hold reason is required.");Action<SqlCommand,string,object,object> history=(cmd,field,a,b)=>{if(Convert.ToString(a)==Convert.ToString(b))return;cmd.CommandText+="INSERT dbo.SRM_History(RequestID,FieldName,OldValue,NewValue,Remarks,ChangedBy) VALUES(@ID"+field+",@F"+field+",@O"+field+",@N"+field+",@Remarks"+field+",@By"+field+");";Add(cmd,"@ID"+field,id);Add(cmd,"@F"+field,field);Add(cmd,"@O"+field,a);Add(cmd,"@N"+field,b);Add(cmd,"@Remarks"+field,update);Add(cmd,"@By"+field,by);};using(var c=new SqlCommand("",cn,tr)){history(c,"Status",old["StatusCode"],status);history(c,"Priority",old["FinalPriority"],finalPriority);history(c,"Assignment",old["AssignedDeveloperID"],developerId);history(c,"Start",old["ExpectedStartDate"],start);history(c,"Completion",old["ExpectedCompletionDate"],completion);history(c,"Hold Reason",old["HoldReason"],status=="On Hold"?holdReason:null);if(!String.IsNullOrWhiteSpace(update))history(c,"Update",old["LatestUpdate"],update);if(c.CommandText.Length>0)c.ExecuteNonQuery();}using(var c=new SqlCommand(@"UPDATE dbo.SRM_Request SET AssignedDeveloperID=NULLIF(@Dev,0),AssignedDeveloperName=@DevName,FinalPriority=@Priority,StatusCode=@Status,ExpectedStartDate=@Start,ExpectedCompletionDate=@Completion,ActualCompletionDate=CASE WHEN @Status='Completed' THEN ISNULL(ActualCompletionDate,CAST(GETDATE() AS date)) ELSE NULL END,LatestUpdate=@Update,HoldReason=CASE WHEN @Status='On Hold' THEN @Hold ELSE NULL END,UpdatedBy=@By,UpdatedOn=SYSDATETIME() WHERE RequestID=@ID",cn,tr)){Add(c,"@Dev",developerId);Add(c,"@DevName",developerName);Add(c,"@Priority",finalPriority);Add(c,"@Status",status);Add(c,"@Start",start);Add(c,"@Completion",completion);Add(c,"@Update",update);Add(c,"@Hold",holdReason);Add(c,"@By",by);Add(c,"@ID",id);c.ExecuteNonQuery();}tr.Commit();return notify;}catch{tr.Rollback();throw;}}
  public DataTable Notification(long id){using(var cn=Open())using(var c=new SqlCommand(@"SELECT r.RequestNo,r.Title,r.RequestOwnerCode,r.RequestedByName,r.StatusCode,r.LatestUpdate,r.ExpectedCompletionDate,r.AssignedDeveloperName,requester.OfficialEmailID RequesterEmail,developer.OfficialEmailID DeveloperEmail FROM dbo.SRM_Request r LEFT JOIN dbo.EmployeeInfo requester ON requester.EmployeeID=r.RequestedBy LEFT JOIN dbo.EmployeeInfo developer ON developer.EmployeeID=r.AssignedDeveloperID WHERE r.RequestID=@ID",cn)){Add(c,"@ID",id);return Table(c);}}
  public DataTable Emails(string[] codes){using(var cn=Open())using(var c=new SqlCommand("SELECT OfficialEmailID FROM dbo.EmployeeInfo WHERE Code IN (@A,@B,@C) AND NULLIF(OfficialEmailID,'') IS NOT NULL",cn)){Add(c,"@A",codes.Length>0?codes[0]:"");Add(c,"@B",codes.Length>1?codes[1]:"");Add(c,"@C",codes.Length>2?codes[2]:"");return Table(c);}}
  public DataTable DeveloperReport(int developerId,string scope){using(var cn=Open())using(var c=new SqlCommand(@"SELECT r.AssignedDeveloperName Developer,r.RequestNo,r.Title,a.ApplicationName,m.ModuleName,r.StatusCode,r.ExpectedCompletionDate,r.ActualCompletionDate,CASE WHEN r.StatusCode='Completed' THEN CASE WHEN r.ExpectedCompletionDate IS NULL THEN 'Completed - No Target' WHEN r.ActualCompletionDate<=r.ExpectedCompletionDate THEN 'Completed In Time' ELSE 'Completed Delayed' END WHEN r.StatusCode='On Hold' THEN 'On Hold' WHEN r.ExpectedCompletionDate IS NULL THEN 'No Timeline' WHEN r.ExpectedCompletionDate<CAST(GETDATE() AS date) THEN 'Delayed' ELSE 'In Time' END DeliveryStatus,r.LatestUpdate FROM dbo.SRM_Request r JOIN dbo.SRM_Application a ON a.ApplicationID=r.ApplicationID LEFT JOIN dbo.SRM_Module m ON m.ModuleID=r.ModuleID WHERE r.IsDeleted=0 AND r.AssignedDeveloperID IS NOT NULL AND (@Developer=0 OR r.AssignedDeveloperID=@Developer) AND ((@Scope='Current' AND r.StatusCode NOT IN('Completed','Rejected','Cancelled')) OR (@Scope='Completed' AND r.StatusCode='Completed') OR @Scope='All') ORDER BY r.AssignedDeveloperName,CASE WHEN r.StatusCode='Completed' THEN 1 ELSE 0 END,ISNULL(r.ExpectedCompletionDate,'99991231')",cn)){Add(c,"@Developer",developerId);Add(c,"@Scope",scope??"Current");return Table(c);}}
  public void AddAttachment(long id,int by,string original,string stored,string type,long size){using(var cn=Open())using(var c=new SqlCommand("IF NOT EXISTS(SELECT 1 FROM dbo.SRM_Request WHERE RequestID=@ID AND RequestedBy=@By) THROW 50001,'Access denied.',1;INSERT dbo.SRM_Attachment(RequestID,OriginalFileName,StoredFileName,ContentType,FileSize,UploadedBy) VALUES(@ID,@Original,@Stored,@Type,@Size,@By);",cn)){Add(c,"@ID",id);Add(c,"@By",by);Add(c,"@Original",original);Add(c,"@Stored",stored);Add(c,"@Type",type);Add(c,"@Size",size);c.ExecuteNonQuery();}}
  public DataTable Attachment(long id,int employeeId,bool canViewAll){using(var cn=Open())using(var c=new SqlCommand("SELECT a.* FROM dbo.SRM_Attachment a JOIN dbo.SRM_Request r ON r.RequestID=a.RequestID WHERE a.AttachmentID=@ID AND a.IsActive=1 AND (@All=1 OR r.RequestedBy=@E)",cn)){Add(c,"@ID",id);Add(c,"@E",employeeId);Add(c,"@All",canViewAll);return Table(c);}}
 }
}
