SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF COL_LENGTH('dbo.SRM_Request','RequestOwnerCode') IS NOT NULL
    ALTER TABLE dbo.SRM_Request ALTER COLUMN RequestOwnerCode varchar(500) NULL;
COMMIT TRANSACTION;
