using System;
using System.Collections.Generic;
namespace WebPortal.Assets.Classes
{
 public class ApiResult { public bool Success{get;set;} public string Message{get;set;} public object Data{get;set;} public static ApiResult Ok(object d=null,string m="Saved successfully."){return new ApiResult{Success=true,Message=m,Data=d};} public static ApiResult Fail(string m){return new ApiResult{Success=false,Message=m};} }
 public class MasterInput { public int ID{get;set;} public int? ParentID{get;set;} public int? CompanyID{get;set;} public string Name{get;set;} public string Code{get;set;} public string Description{get;set;} public string Address{get;set;} public string ContactPerson{get;set;} public string PhoneNumber{get;set;} public string EmailAddress{get;set;} public string GSTNumber{get;set;} public string PANNumber{get;set;} public string FaxNumber{get;set;} public string WebsiteURL{get;set;} public string AccountHolderName{get;set;} public string BankName{get;set;} public string BankBranchAddress{get;set;} public string AccountType{get;set;} public string AccountNumber{get;set;} public string MICRCode{get;set;} public string IFSCCode{get;set;} public bool IsActive{get;set;} public bool Flag1{get;set;} public bool Flag2{get;set;} public bool Flag3{get;set;} public int? Number1{get;set;} public string Extra1{get;set;} public string Extra2{get;set;} public string Extra3{get;set;} public string Extra4{get;set;} }
 public class CategoryAccessInput { public long UserID{get;set;} public List<int> CategoryIDs{get;set;} }
 public class AssetInput { public long AssetID{get;set;} public string AssetCode{get;set;} public string AssetTagNumber{get;set;} public string Barcode{get;set;} public string QRCode{get;set;} public string SerialNumber{get;set;} public string IMEINumber{get;set;} public string HostName{get;set;} public int AssetCategoryID{get;set;} public int AssetTypeID{get;set;} public int? AssetBrandID{get;set;} public int? AssetModelID{get;set;} public string AssetDescription{get;set;} public int? VendorID{get;set;} public string InvoiceNumber{get;set;} public DateTime? InvoiceDate{get;set;} public DateTime? PurchaseDate{get;set;} public decimal PurchaseValue{get;set;} public DateTime? WarrantyStartDate{get;set;} public DateTime? WarrantyEndDate{get;set;} public int CurrentBranchID{get;set;} public int? AssetStatusID{get;set;} public string AssetCondition{get;set;} public string Processor{get;set;} public string RAM{get;set;} public string Storage{get;set;} public string OperatingSystem{get;set;} public string IPAddress{get;set;} public string MACAddress{get;set;} public string Accessories{get;set;} public string Remarks{get;set;} }
 public class PurchaseRequestInput { public long PurchaseRequestID{get;set;} public string RequestNumber{get;set;} public DateTime RequestDate{get;set;} public long RequestedBy{get;set;} public long? DepartmentID{get;set;} public int BranchID{get;set;} public string Priority{get;set;} public DateTime? RequiredByDate{get;set;} public string BusinessJustification{get;set;} public string Remarks{get;set;} public List<PurchaseRequestItemInput> Items{get;set;} }
 public class PurchaseRequestItemInput { public int? AssetCategoryID{get;set;} public int? AssetTypeID{get;set;} public int? PreferredBrandID{get;set;} public string ItemDescription{get;set;} public string TechnicalSpecification{get;set;} public int RequiredQuantity{get;set;} public decimal EstimatedUnitCost{get;set;} public string Remarks{get;set;} }
 public class QuotationInput { public long QuotationID{get;set;} public string QuotationNumber{get;set;} public int VendorID{get;set;} public long? PurchaseRequestID{get;set;} public DateTime QuotationDate{get;set;} public DateTime? ValidUntilDate{get;set;} public string ReferenceNumber{get;set;} public string DeliveryPeriod{get;set;} public string PaymentTerms{get;set;} public string WarrantyTerms{get;set;} public string Remarks{get;set;} public List<QuotationItemInput> Items{get;set;} }
 public class QuotationItemInput { public int? AssetCategoryID{get;set;} public int? AssetTypeID{get;set;} public int? AssetBrandID{get;set;} public int? AssetModelID{get;set;} public string ItemDescription{get;set;} public int Quantity{get;set;} public decimal UnitPrice{get;set;} public decimal DiscountAmount{get;set;} public decimal TaxPercentage{get;set;} public string WarrantyPeriod{get;set;} public string DeliveryTime{get;set;} }
 public class PurchaseOrderInput { public long PurchaseOrderID{get;set;} public string PurchaseOrderNumber{get;set;} public DateTime PurchaseOrderDate{get;set;} public int VendorID{get;set;} public long? QuotationID{get;set;} public long? PurchaseRequestID{get;set;} public int BranchID{get;set;} public string BillingAddress{get;set;} public string ShippingAddress{get;set;} public DateTime? ExpectedDeliveryDate{get;set;} public string PaymentTerms{get;set;} public string CurrencyCode{get;set;} public decimal FreightCharges{get;set;} public decimal OtherCharges{get;set;} public string Remarks{get;set;} public List<PurchaseOrderItemInput> Items{get;set;} public List<string> Terms{get;set;} }
 public class PurchaseOrderItemInput { public int? AssetCategoryID{get;set;} public int? AssetTypeID{get;set;} public int? AssetBrandID{get;set;} public int? AssetModelID{get;set;} public string ItemDescription{get;set;} public int OrderedQuantity{get;set;} public decimal UnitPrice{get;set;} public decimal DiscountAmount{get;set;} public decimal TaxPercentage{get;set;} public string WarrantyPeriod{get;set;} }
 public class ReceiptInput { public long ReceiptID{get;set;} public string ReceiptNumber{get;set;} public long? PurchaseOrderID{get;set;} public int VendorID{get;set;} public int BranchID{get;set;} public DateTime ReceiptDate{get;set;} public string InvoiceNumber{get;set;} public DateTime? InvoiceDate{get;set;} public string DeliveryChallanNumber{get;set;} public string Remarks{get;set;} public List<ReceiptItemInput> Items{get;set;} }
 public class ReceiptItemInput { public long? PurchaseOrderItemID{get;set;} public int OrderedQuantity{get;set;} public int PreviouslyReceivedQuantity{get;set;} public int CurrentReceivedQuantity{get;set;} public int RejectedQuantity{get;set;} public string ConditionOnReceipt{get;set;} public string SerialNumbers{get;set;} public string Remarks{get;set;} }
 public class AllocationInput { public long AllocationID{get;set;} public long AssetID{get;set;} public string AllocationType{get;set;} public long? EmployeeID{get;set;} public long? DepartmentID{get;set;} public long? ProjectID{get;set;} public int BranchID{get;set;} public DateTime AllocationDate{get;set;} public DateTime? ExpectedReturnDate{get;set;} public string AssetConditionAtAllocation{get;set;} public string AccessoriesIssued{get;set;} public string Purpose{get;set;} public string Remarks{get;set;} }
 public class AllocationBatchInput { public List<long> AssetIDs{get;set;} public long EmployeeID{get;set;} public int ShiftID{get;set;} public string ShiftName{get;set;} public int BranchID{get;set;} public DateTime AllocationDate{get;set;} public DateTime? ExpectedReturnDate{get;set;} public string AssetConditionAtAllocation{get;set;} public string AccessoriesIssued{get;set;} public string Purpose{get;set;} public string Remarks{get;set;} public int? AssetStatusID{get;set;} }
 public class EmployeeITFieldInput { public int FieldID{get;set;} public string FieldLabel{get;set;} public string FieldCode{get;set;} public string FieldType{get;set;} public int DisplayOrder{get;set;} public bool IsRequired{get;set;} public bool IsActive{get;set;} public string DependsOnFieldCode{get;set;} public string DependsOnValue{get;set;} }
 public class EmployeeITValueInput { public int FieldID{get;set;} public string FieldValue{get;set;} }
 public class EmployeeITProfileInput { public long EmployeeID{get;set;} public List<EmployeeITValueInput> Values{get;set;} }
 public class ReturnInput { public long AllocationID{get;set;} public DateTime ReturnDate{get;set;} public string ConditionAtReturn{get;set;} public string AccessoriesReturned{get;set;} public string MissingAccessories{get;set;} public string DamageDetails{get;set;} public int ReturnBranchID{get;set;} public int? NextStatusID{get;set;} public decimal RecoveryAmount{get;set;} public string Remarks{get;set;} }
 public class TransferInput { public long TransferID{get;set;} public long AssetID{get;set;} public int FromBranchID{get;set;} public int ToBranchID{get;set;} public DateTime TransferDate{get;set;} public DateTime? ExpectedReceiptDate{get;set;} public string TransferReason{get;set;} public string CourierName{get;set;} public string TrackingNumber{get;set;} public string Remarks{get;set;} }
 public class MaintenanceInput { public long MaintenanceID{get;set;} public long AssetID{get;set;} public DateTime ComplaintDate{get;set;} public string ProblemDescription{get;set;} public string Priority{get;set;} public long? AssignedTo{get;set;} public int? VendorID{get;set;} public DateTime? ExpectedCompletionDate{get;set;} public string Diagnosis{get;set;} public string RepairAction{get;set;} public string PartsReplaced{get;set;} public decimal RepairCost{get;set;} public decimal ServiceCharge{get;set;} public bool WarrantyClaimed{get;set;} public string Remarks{get;set;} }
 public class DisposalInput { public long DisposalID{get;set;} public long AssetID{get;set;} public DateTime DisposalRequestDate{get;set;} public int DisposalReasonID{get;set;} public string ProposedDisposalMethod{get;set;} public decimal CurrentBookValue{get;set;} public decimal SaleValue{get;set;} public string BuyerName{get;set;} public string ScrapVendor{get;set;} public string Remarks{get;set;} }
}
