var ticketId=+(new URLSearchParams(location.search).get('id')||0),ticketData=null;
IHMS.shell('Ticket Details','Manage assignment, approval and progress');
function fmtDate(v){if(!v)return '—';var m=/\/Date\((-?\d+)/.exec(v),d=m?new Date(+m[1]):new Date(v);return isNaN(d.getTime())?IHMS.esc(v):d.toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function plainText(v){var doc=new DOMParser().parseFromString(v||'','text/html');$(doc).find('head,style,script,meta,link').remove();var t=(doc.body.textContent||'').replace(/\u00a0/g,' ').replace(/\r/g,'\n');var q=t.search(/^\s*(?:-{2,}\s*Original Message\s*-{2,}|On .+ wrote:|From:\s).*$/im);if(q<0){var h=/\bFrom:\s.+?\bSent:\s/i.exec(t);q=h?h.index:-1}if(q>0)t=t.substring(0,q);return t.replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
function options(rows,placeholder){return '<option value="">'+placeholder+'</option>'+(rows||[]).map(function(x){return '<option value="'+x.EmployeeID+'">'+IHMS.esc(x.DisplayName)+'</option>'}).join('')}
function activityLabel(value){var labels={PublicRemark:'Update shared with requester',InternalNote:'Internal note',ApprovalRequested:'Approval requested',ApprovalDecision:'Approval decision',RequestType:'Request type changed',InboundEmail:'Email received'};return labels[value]||String(value||'').replace(/([a-z])([A-Z])/g,'$1 $2')}
function employeeName(value){if(!value)return '';var text=$('#assign option[value="'+value+'"],#approver option[value="'+value+'"]').first().text();return text||String(value)}
function activityValue(activity,value){if(!value)return '';if(activity==='Assignment'||activity==='ApprovalRequested')return employeeName(value);if(activity==='RequestType')return $('#type option[value="'+value+'"]').text()||value;return value}
function boot(){IHMS.post('TicketDetails.aspx/Masters',{},function(m){$('#type').html(m[0].filter(function(x){return x.IsActive}).map(function(x){return '<option value="'+x.RequestTypeID+'">'+IHMS.esc(x.Name)+'</option>'}).join(''));$('#status').html(m[1].map(function(x){return '<option value="'+x.StatusCode+'">'+IHMS.esc(x.StatusName)+'</option>'}).join(''));IHMS.post('TicketDetails.aspx/People',{},function(p){$('#assign').html(options(p[0],'Select IT employee'));$('#approver').html(options(p[1],'Select domain head'));$('#branch').html('<option value="">Select branch</option>'+(p[2]||[]).map(function(x){return '<option value="'+IHMS.esc(x.BranchName)+'">'+IHMS.esc(x.BranchName)+'</option>'}).join(''));$('.employee-select').select2({width:'100%',allowClear:true});loadTicket()})})}
function loadTicket(){IHMS.post('TicketDetails.aspx/Get',{ticketId:ticketId},function(d){var x=d[0][0];if(!x){IHMS.toast('Ticket not found',true);return}ticketData=x;var locked=x.StatusCode==='PendingApproval';$('#lock').toggle(locked);$('.edit').prop('disabled',locked);if(x.RequestTypeID)$('#type').val(x.RequestTypeID);else $('#type option').filter(function(){return $(this).text()===x.RequestType}).prop('selected',true);$('#status').val(x.StatusCode);$('#assign').val(x.AssignedToEmployeeID||'').trigger('change.select2');$('#branch').val(x.Location||'').trigger('change.select2');$('#ticket').html('<div class="panel-body"><div class="ticket-top"><div><div class="ticket-number">'+IHMS.esc(x.TicketNo)+'</div><div class="ticket-subject">'+IHMS.esc(x.Subject)+'</div></div><div class="ticket-badges">'+IHMS.status(x.StatusName)+' '+IHMS.priority(x.PriorityName)+(x.IsOverdue?'<span class="badge-sla">SLA breached</span>':'')+'</div></div><div class="ticket-meta"><div><span class="meta-label">Requestor</span><span class="meta-value">'+IHMS.esc(x.RequestorName)+'</span><small>'+IHMS.esc(x.RequestorEmail)+'</small></div><div><span class="meta-label">Department</span><span class="meta-value">'+IHMS.esc(x.Department||'—')+'</span></div><div><span class="meta-label">Branch</span><span class="meta-value">'+IHMS.esc(x.Location||'—')+'</span></div><div><span class="meta-label">Desk No.</span><span class="meta-value">'+IHMS.esc(x.DeskNo||'—')+'</span></div><div><span class="meta-label">Request type</span><span class="meta-value">'+IHMS.esc(x.RequestType||'Unclassified')+'</span></div><div><span class="meta-label">Assigned to</span><span class="meta-value">'+IHMS.esc($('#assign option[value="'+(x.AssignedToEmployeeID||'')+'"]').text()||'Main Bucket')+'</span></div></div><div class="ticket-description">'+IHMS.esc(plainText(x.Description))+'</div><div class="ticket-dates"><span><b>Created:</b> '+fmtDate(x.CreatedDate)+'</span><span><b>Updated:</b> '+fmtDate(x.ModifiedDate)+'</span><span><b>SLA due:</b> '+fmtDate(x.SLADueDate)+'</span></div></div>');$('#timeline').html((d[1]||[]).map(function(a){return '<div class="event '+(a.IsInternal?'internal':'')+'"><b>'+IHMS.esc(activityLabel(a.ActivityType))+'</b> '+IHMS.esc(a.OldValue||'')+(a.OldValue?' → ':'')+IHMS.esc(a.NewValue||'')+'<div>'+IHMS.esc(plainText(a.Details||''))+'</div><small>'+IHMS.esc(a.PerformedName||a.PerformedBy||'System')+' · '+fmtDate(a.PerformedDate)+'</small></div>'}).join('')||'No activity');$('#attachments').html((d[2]||[]).map(function(a){return '<div class="mb-2"><i class="fas fa-paperclip text-info"></i> '+IHMS.esc(a.OriginalFileName)+'<br><small>'+fmtDate(a.UploadedDate)+'</small></div>'}).join('')||'No attachments')})}
function done(){IHMS.toast('Ticket updated');$('#remark').val('');loadTicket()}
function changeType(){IHMS.post('TicketDetails.aspx/ChangeType',{ticketId:ticketId,requestTypeId:+$('#type').val()},done)}
function assignTicket(){var employee=+$('#assign').val();if(!employee){IHMS.toast('Select an IT employee',true);return}IHMS.post('TicketDetails.aspx/Assign',{ticketId:ticketId,employeeId:employee},done)}
function transition(){IHMS.post('TicketDetails.aspx/Transition',{ticketId:ticketId,status:$('#status').val(),remark:$('#remark').val()},done)}
function addRemark(internalNote){var remark=$.trim($('#remark').val());if(!remark){IHMS.toast('Enter a remark or internal note',true);$('#remark').focus();return}IHMS.post('TicketDetails.aspx/AddRemark',{ticketId:ticketId,remark:remark,internalNote:internalNote},done)}
function changeLocation(){var location=$('#branch').val();if(!location){IHMS.toast('Select a branch',true);return}IHMS.post('TicketDetails.aspx/ChangeLocation',{ticketId:ticketId,location:location},done)}
function approval(){var employee=+$('#approver').val();if(!employee){IHMS.toast('Select an approver',true);return}IHMS.post('TicketDetails.aspx/RequestApproval',{ticketId:ticketId,approverId:employee,remark:$('#remark').val()},done)}
$('#upload').on('submit',function(e){e.preventDefault();var input=$(this).find('input[type=file]')[0];if(!input.files.length){IHMS.toast('Select a file to upload',true);return}var f=new FormData(this);f.append('ticketId',ticketId);$('#ihms-loading').css('display','flex').appendTo(document.body);$.ajax({url:'TicketDetails.aspx?upload=1',method:'POST',data:f,processData:false,contentType:false}).done(done).fail(function(x){IHMS.toast(x.responseText||'Upload failed',true)}).always(function(){$('#ihms-loading').hide()})});
$(boot);
