<%@ Page Language="C#" MasterPageFile="~/US/USAdmin.Master" AutoEventWireup="true" CodeBehind="ProjectProcessLoanReport.aspx.cs" Inherits="WebPortal.US.ProjectProcessLoanReport" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<script src="https://cdn.sheetjs.com/xlsx-latest/package/dist/xlsx.full.min.js"></script>
<style>.ppr{padding:18px}.ppr-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:20px;margin-bottom:18px}.ppr-head{background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;border-radius:18px;padding:22px;margin-bottom:18px}.ppr-filter{display:flex;gap:12px;align-items:end}.ppr-filter>div{min-width:280px}.ppr label{display:block;font-weight:700;margin-bottom:6px}.ppr select{width:100%;height:40px;border:1px solid #d7deea;border-radius:10px;padding:7px}.ppr button{height:40px;border:0;border-radius:10px;padding:0 20px;background:#2563eb;color:#fff;font-weight:700}.ppr-table{overflow:auto}.ppr th{white-space:nowrap;text-align:center!important;}.ppr td{white-space:nowrap}</style>
<script>
var pprTable,pprExportTableHtml='';
$(function(){pprLoadProjects();});
function pprPost(method,data,ok){$.ajax({url:'ProjectProcessLoanReport.aspx/'+method,type:'POST',contentType:'application/json; charset=utf-8',data:JSON.stringify(data||{}),success:function(r){ok(JSON.parse(r.d||'[]'));},error:function(e){Swal.fire('Error',e.responseText||'Unable to load report.','error');}});}
function pprValue(r,names){for(var i=0;i<names.length;i++)if(r[names[i]]!==undefined&&r[names[i]]!==null)return r[names[i]];return '';}
function pprLoadProjects(){pprPost('GetProjects',{},function(rows){var d=$('#ppr_project').empty().append('<option value="">Select</option>');$.each(rows,function(_,r){var id=pprValue(r,['ProjectID','ProjectId','ID']),name=pprValue(r,['ProjectName','ProjectNo','ProjectNumber','Client']);d.append($('<option/>').val(id).text(name));});});}
function pprLoad(){var o=$('#ppr_project option:selected'),id=parseInt(o.val(),10)||0,name=o.text();if(!id){Swal.fire('Validation','Please select project.','warning');return false;}pprPost('GetReport',{ProjectID:id,ProjectNumber:name},pprRender);return false;}
function pprEsc(v){return $('<div/>').text(v==null?'':v).html();}
function pprRender(result){if(pprTable){pprTable.destroy();pprTable=null;}var processes=result.Processes||[],rows=result.Rows||[],h1='<tr><th rowspan="2">Project #</th><th rowspan="2">Loan #</th>',h2='<tr>';$.each(processes,function(_,p){h1+='<th colspan="4">'+pprEsc(p.ProcessName)+'</th>';h2+='<th>Employee</th><th>Start Date</th><th>End Date</th><th>Status</th>';});h1+='</tr>';h2+='</tr>';var body='';$.each(rows,function(_,r){body+='<tr><td>'+pprEsc(r.ProjectNumber)+'</td><td>'+pprEsc(r.LoanNo)+'</td>';$.each(processes,function(_,p){var x=(r.Processes||{})[String(p.ProcessName)]||{};body+='<td>'+pprEsc(x.Employee)+'</td><td>'+pprEsc(x.StartDate)+'</td><td>'+pprEsc(x.EndDate)+'</td><td>'+pprEsc(x.Status)+'</td>';});body+='</tr>';});$('#ppr_table thead').html(h1+h2);$('#ppr_table tbody').html(body);pprExportTableHtml=$('#ppr_table')[0].outerHTML;pprTable=$('#ppr_table').DataTable({dom:'Bfrtip',scrollX:true,ordering:false,pageLength:25,buttons:[{text:'Excel',className:'buttons-excel',action:pprExport}]});}
function pprExport(){if(typeof XLSX==='undefined'){Swal.fire('Export unavailable','Excel library could not be loaded.','error');return;}var holder=document.createElement('div');holder.innerHTML=pprExportTableHtml;var workbook=XLSX.utils.table_to_book(holder.querySelector('table'),{sheet:'Loan Process Report'});XLSX.writeFile(workbook,'Project_Process_Loan_Report.xlsx');}
</script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server"><div class="ppr"><div class="ppr-head"><h3>Project Process Loan Report</h3><div>Project-wise loan status across all configured processes.</div></div><div class="ppr-card ppr-filter"><div><label>Project</label><select id="ppr_project"></select></div><button type="button" onclick="return pprLoad();">View Report</button></div><div class="ppr-card ppr-table"><table id="ppr_table" class="table table-bordered" style="width:100%"><thead></thead><tbody></tbody></table></div></div></asp:Content>
