//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Feedback
{
    public partial class AddFeedbackForSearchProject
    {
    }
}
