<%@ Page Title="Software Request Tracker" Language="C#" MasterPageFile="~/IT/Admin.Master" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="WebPortal.SoftwareRequests.Dashboard" %>
<asp:Content ID="H" ContentPlaceHolderID="head" runat="server"><link href="../Content/software-requests.css?v=6" rel="stylesheet" /></asp:Content>
<asp:Content ID="B" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="srm"><div class="srm-head"><div><h3>Software Request &amp; Task Tracker</h3><span>Request visibility, software queue and delivery timeline</span></div><button type="button" class="srm-btn" onclick="SRM.show('new')"><i class="fas fa-plus"></i> New Request</button></div><div id="srmAlert" class="srm-alert"></div>
<div class="srm-grid"><div class="srm-kpi k-new">New<b data-kpi="NewCount">0</b></div><div class="srm-kpi k-progress">In Progress<b data-kpi="InProgressCount">0</b></div><div class="srm-kpi k-hold">On Hold<b data-kpi="OnHoldCount">0</b></div><div class="srm-kpi k-test">Testing<b data-kpi="TestingCount">0</b></div><div class="srm-kpi k-done">Completed<b data-kpi="CompletedCount">0</b></div></div>
<div class="srm-tabs"><button type="button" data-view="list" class="active">Requests / Task Queue</button><button type="button" data-view="new">New Request</button><button type="button" data-view="detail">Request Detail</button><button type="button" data-view="report" onclick="SRM.loadReport()">Developer Report</button></div>
<section id="view-list" class="srm-view"><div class="srm-card"><div class="srm-filters"><select id="fScope"><option value="Mine">My Requests</option><option value="All">All Requests / Queue</option></select><input id="fSearch" placeholder="Request ID or title"/><input id="fRequester" placeholder="Requester"/><input id="fDepartment" placeholder="Department"/><select id="fApplication"></select><select id="fModule"></select><select id="fDeveloper"></select><select id="fPriority"></select><select id="fStatus"></select><button type="button" class="srm-btn" onclick="SRM.loadList()">Search</button><button type="button" class="srm-btn alt" onclick="SRM.exportCsv()">Export CSV</button></div><div class="srm-table-wrap"><table id="requestTable" class="srm-table"><thead><tr><th>Request ID</th><th>Date</th><th>Request</th><th>Software</th><th>Module</th><th>Requested By</th><th>Priority</th><th>Assigned To</th><th>Status</th><th>Expected Completion</th><th>Last Update</th></tr></thead><tbody id="requestRows"></tbody></table></div></div></section>
<section id="view-new" class="srm-view srm-hidden"><div class="srm-card compact"><h4>New Software Request</h4><div class="srm-profile"><b id="profileName"></b><span id="profileDepartment"></span></div><div class="srm-form"><div><label>Request Type *</label><select id="rqType"></select></div><div><label>Requested Priority *</label><select id="rqPriority"></select></div><div><label>Software / Application *</label><select id="rqApp"></select></div><div><label>Module</label><select id="rqModule"></select></div><div class="wide"><label>Title *</label><input id="rqTitle" maxlength="250"/></div><div class="wide"><label>Requirement / Description *</label><textarea id="rqDescription"></textarea></div><div class="wide"><label>Business Justification *</label><textarea id="rqJustification"></textarea></div><div><label>Required By Date</label><input id="rqDate" type="date"/></div><div><label>Attachment (optional, max 5 MB)</label><input id="rqAttachment" type="file" accept=".pdf,.png,.jpg,.jpeg,.doc,.docx,.xls,.xlsx"/></div></div><button type="button" class="srm-btn" onclick="SRM.create()">Submit Request</button></div></section>
<section id="view-report" class="srm-view srm-hidden"><div class="srm-card"><h4>Developer Task Report</h4><div class="srm-filters"><select id="rDeveloper"></select><select id="rScope"><option value="Current">Current Tasks</option><option value="Completed">Completed Tasks</option><option value="All">All Tasks</option></select><button type="button" class="srm-btn" onclick="SRM.loadReport()">View</button></div><div class="srm-table-wrap"><table class="srm-table"><thead><tr><th>Developer</th><th>Request ID</th><th>Task</th><th>Software</th><th>Module</th><th>Status</th><th>Expected</th><th>Completed</th><th>Delivery</th><th>Latest Update</th></tr></thead><tbody id="reportRows"></tbody></table></div></div></section>
<section id="view-detail" class="srm-view srm-hidden"><div class="srm-card"><div class="srm-detail-head"><div><h4 id="dTitle">Select a request</h4><div id="dMeta"></div></div><button type="button" class="srm-btn alt" onclick="SRM.show('list')">Back</button></div><div class="srm-detail-grid"><div><label>Description</label><p id="dDescription"></p></div><div><label>Business Justification</label><p id="dJustification"></p></div><div><label>Latest Update</label><p id="dUpdate"></p></div><div><label>Timeline</label><p id="dTimeline"></p></div></div></div>
<div id="teamPanel" class="srm-card srm-hidden"><h4>Software Team Update</h4><div class="srm-form"><div><label>Assigned Developer</label><select id="uDeveloper"></select></div><div><label>Final Priority</label><select id="uPriority"></select></div><div><label>Status</label><select id="uStatus"></select></div><div><label>Expected Start</label><input id="uStart" type="date"/></div><div><label>Expected Completion</label><input id="uCompletion" type="date"/></div><div class="wide"><label>Developer Remarks / Latest Update</label><textarea id="uUpdate"></textarea></div><div class="wide" id="holdBox"><label>On Hold Reason</label><input id="uHold" maxlength="500"/></div><div class="wide"><label>Testing email override (optional)</label><input id="uTestEmail" type="email" placeholder="Send only to this address during testing"/></div></div><button type="button" class="srm-btn" onclick="SRM.update()">Save Task Update</button></div>
<div class="srm-card"><h4>Updates Till Date</h4><div class="srm-table-wrap"><table class="srm-table srm-history-table"><thead><tr><th>Date</th><th>Assigned Developer</th><th>Status</th><th>Expected Completion Date</th><th>Developer Remark</th><th>Hold Reason</th></tr></thead><tbody id="historyRows"></tbody></table></div></div></section></div>
<script src="../Scripts/software-requests.js?v=6"></script>
</asp:Content>
