//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal
{
    public partial class OrderProcessManagement
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
