//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Tracking
{
    public partial class UpdateDispatchDate
    {
    }
}