//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Accounts
{
    public partial class DiwaliExpenses
    {
    }
}
