//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Admin
{
    public partial class EmployeeLogReport
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlEmployee;
    }
}
