<%@ Page Title="Error Type Master" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="ErrorTypeMaster.aspx.cs" Inherits="WebPortal.Admin.ErrorTypeMaster" %>
<asp:Content ID="h" ContentPlaceHolderID="head" runat="server"><style>
.etm{color:#172737}.etm-hero{background:linear-gradient(135deg,#0f766e,#1d4ed8);color:#fff;padding:20px 24px;border-radius:8px;margin-bottom:18px}.etm-card{background:#fff;border:1px solid #dce5ec;border-radius:8px;margin-bottom:18px}.etm-title{padding:15px 18px;border-bottom:1px solid #e7edf2;font-weight:700}.etm-body{padding:18px}.etm-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px 16px;align-items:end}.etm-field[hidden]{display:none!important}.etm-field label{display:block;font-size:12px;font-weight:700;margin-bottom:6px}.etm-table-wrap{overflow:auto;max-height:600px}.etm table{width:100%;border-collapse:collapse}.etm th,.etm td{padding:9px 11px;border-bottom:1px solid #e2e9ef;font-size:12px;white-space:nowrap;text-align:left}.etm th{position:sticky;top:0;background:#edf3f6}.etm button{border:0;border-radius:6px;padding:8px 14px;font-weight:700}.etm-add{background:#0f766e;color:#fff}.etm-toggle{border:1px solid #cbd5e1!important;background:#fff}@media(max-width:800px){.etm-grid{grid-template-columns:1fr 1fr}}
.etm-message{display:none;margin-bottom:14px;padding:10px 14px;border-radius:6px;font-size:13px;font-weight:700}.etm-message.success{display:block;background:#dcfce7;color:#166534}.etm-message.error{display:block;background:#fee2e2;color:#991b1b}
</style><script>
$(function(){$('.etm-hero').after('<div id="etmMessage" class="etm-message" role="status"></div>');$('#etmType').on('change',loadEtm);$('#etmAdd').on('click',addEtm);loadEtm()});
function etmCall(m,p){return $.ajax({url:'ErrorTypeMaster.aspx/'+m,type:'POST',data:JSON.stringify(p),contentType:'application/json; charset=utf-8',dataType:'json'})}
function etmMessage(text,type){$('#etmMessage').removeClass('success error').addClass(type).text(text)}
function etmError(x){etmMessage((x.responseJSON&&x.responseJSON.Message)||'Operation failed.','error')}
function loadEtm(){var t=Number($('#etmType').val()),parent=[2,3,5,6,7].indexOf(t)>=0;$('#etmParentField').prop('hidden',!parent);$('#etmParentLabel').text(t===5?'Taxonomy':'Parent Error Type');$('#etmNameLabel').text('Error Type '+t+' Name');etmCall('GetParents',{ErrorType:t}).done(function(r){var a=JSON.parse(r.d||'[]'),p=$('#etmParent').empty().append($('<option>').val('').text('Select'));$.each(a,function(_,x){p.append($('<option>').val(x.ID).text(x.Name))})});etmCall('GetErrorTypes',{ErrorType:t}).done(function(r){renderEtm(JSON.parse(r.d||'[]'))}).fail(etmError)}
function renderEtm(a){var b=$('#etmRows').empty();$.each(a,function(_,x){var tr=$('<tr>');[x.ID,x.TaxonomyName||'',x.ParentName||'',x.Name,x.DisplayOrder,x.IsActive?'Active':'Disabled'].forEach(function(v){tr.append($('<td>').text(v))});var td=$('<td>').appendTo(tr);$('<button class="etm-toggle" type="button">').text(x.IsActive?'Disable':'Enable').on('click',function(){toggleEtm(x.ID,!x.IsActive)}).appendTo(td);b.append(tr)});if(!a.length)b.append('<tr><td colspan="7">No values found.</td></tr>')}
function addEtm(){var t=Number($('#etmType').val()),n=$.trim($('#etmName').val()),p=Number($('#etmParent').val()||0),o=Number($('#etmOrder').val()||0);if(!n){etmMessage('Name is mandatory.','error');return}if([2,3,5,6,7].indexOf(t)>=0&&!p){etmMessage('Please select a parent.','error');return}etmCall('AddErrorType',{ErrorType:t,Name:n,ParentID:p,DisplayOrder:o}).done(function(){$('#etmName,#etmOrder').val('');loadEtm();etmMessage('Value added successfully.','success')}).fail(etmError)}
function toggleEtm(id,on){if(!window.confirm('Do you want to '+(on?'enable':'disable')+' this value?'))return;etmCall('SetErrorTypeActive',{ErrorType:Number($('#etmType').val()),ID:id,IsActive:on}).done(function(){loadEtm();etmMessage('Value '+(on?'enabled':'disabled')+' successfully.','success')}).fail(etmError)}
</script></asp:Content>
<asp:Content ID="c" ContentPlaceHolderID="ContentPlaceHolder1" runat="server"><div class="etm"><div class="etm-hero"><h2>Error Type Master</h2><div>Add, enable, or disable configurable values.</div></div><div class="etm-card"><div class="etm-title">Add Error Type Value</div><div class="etm-body"><div class="etm-grid"><div class="etm-field"><label>Error Type</label><select id="etmType" class="form-control"><option value="1">Error Type 1</option><option value="2">Error Type 2</option><option value="3">Error Type 3</option><option value="4">Error Type 4</option><option value="5">Error Type 5</option><option value="6">Error Type 6</option><option value="7">Error Type 7</option><option value="8">Error Type 8</option><option value="9">Error Type 9</option></select></div><div id="etmParentField" class="etm-field" hidden><label id="etmParentLabel">Parent</label><select id="etmParent" class="form-control"></select></div><div class="etm-field"><label id="etmNameLabel">Error Type 1 Name</label><input id="etmName" maxlength="500" class="form-control" /></div><div class="etm-field"><label>Display Order (optional)</label><input id="etmOrder" type="number" min="1" class="form-control" /></div><div><button id="etmAdd" class="etm-add" type="button">Add Value</button></div></div></div></div><div class="etm-card"><div class="etm-title">Existing Values</div><div class="etm-table-wrap"><table><thead><tr><th>ID</th><th>Taxonomy</th><th>Parent</th><th>Name</th><th>Order</th><th>Status</th><th>Action</th></tr></thead><tbody id="etmRows"></tbody></table></div></div></div></asp:Content>
